mongodb/docs

- source/includes/warning-copyto-loss-of-type-fidelity.rst
cloneCollection requires that the source and destination collections are on different mongods.  copyTo only works to copy a collection within a database on a single mongod.
Therefore, it is not possible to use cloneCollection instead of copyTo.  As such, we should not suggest the use of cloneCollection where copyTo does not behave as desired, since cloneCollection cannot work for that purpose and it is misleading to suggest that it can.
> cloneCollection is not a viable alternative to copyTo

- source/includes/steps-install-mongodb-enterprise-on-debian.yaml
- source/includes/toc-spec-data-center-awareness.yaml
- source/reference/program/mongostat.txt
Note: The steps thing fixed a build error I was getting. Do with it what you will.
> DOCS-5171 & DOCS-5172: mongostat stat corrections

- source/includes/steps-install-mongodb-enterprise-on-linux.yaml
Needs backporting to 2.6 as well.
> uses desired link for enterprise downloads

- source/core/kerberos.txt
- source/tutorial/troubleshoot-kerberos.txt
If we could cherry-pick this into v3.0 and v2.6, that'd be super. (I'm also happy to push it there myself.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2635)
> DOCS-7997: kerberos conf file is krb5.conf not kerb5.conf

- source/includes/fact-id-field.rst
- source/includes/fact-mws.rst
- source/reference/method/db.collection.insertMany.txt
- source/reference/method/db.collection.insertOne.txt
- source/tutorial/insert-documents.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2753)
> WRITING-1600: MWS integration

- source/meta/images-guide.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2843)
> Add guide to putting images in the corpus

- source/reference/read-preference.txt
This page had an incorrect usage of `readPref()`. I've updated it accordingly.
I also checked, and this is the only incorrect usage across the docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2850)
> Fix readPref usage.

- source/includes/ref-toc-operator-update-field.yaml
Minor text fix for min/max definitions.
Review: https://mongodbcr.appspot.com/138310001
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2897)
> DOCS-10374 Revising min-max definitions for update.txt

- source/reference/operator/aggregation/avg.txt
Should ideally be backported to 3.2 and 3.4, as well.
> DOCS-8996: clarify  behavior with non-existent fields

- source/includes/apiargs-method-db.createCollection-options-param.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2935)
> autoIndexId was not in fact removed in 3.4

- source/reference/explain-results.txt
scanAndOrder is not a field in explain() results as of MongoDB 3.0.
Looks like my editor cleaned line-ending whitespace as well. Sorry about that! The actual change is line 537.
Backport to 3.2 and 3.0 manuals.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2941)
> Specify scanAndOrder removal version

- source/reference/command/findAndModify.txt
For master and 3.4, please.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2943)
> DOCS-10632: upserted response includes _id not nec. ObjectId

- source/reference/command/getMore.txt
- source/release-notes/3.6.txt
added documentation to getMore.txt and 3.6.txt to ensure users only call getMore on cursors they created when authentication is on
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2945)
> Docs 10023 get more with authentication

- source/core/query-optimization.txt
- source/includes/fact-geospatial-index-covered-query.rst
- source/includes/fact-multikey-index-covered-query.rst
- source/release-notes/3.6.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2950)
> DOCS-9937 added section about server tracking metadata for multikey covering

- source/includes/fact-olson-tz-behavior.rst
- source/includes/ref-toc-aggregation-date.yaml
- source/includes/ref-toc-aggregation-operators.yaml
- source/reference/operator/aggregation/dateFromParts.txt
- source/reference/operator/aggregation/dateToParts.txt
- source/reference/operator/aggregation/dateToString.txt
- source/release-notes/3.6.txt
Hi @kay-kim this is ready for a final look and merge into master.
Also updating release notes and aggregation definition toc trees with these new operators.
Code review: https://mongodbcr.appspot.com/158260001/
Staging: 
https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-10475/reference/operator/aggregation.html
https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-10475/reference/operator/aggregation/dateFromParts.html
https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-10475/release-notes/3.6.html
https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-10475/reference/operator/aggregation/dateToParts.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Docs 10475 - New agg operators dateToParts and dateFromParts

- source/reference/method/db.collection.insertMany.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2981)
> DOCS-10486: Add correct BulkWriteError output for db.products.insertMany() example

- source/includes/apiargs-dbcommand-createUser-field.yaml
- source/includes/apiargs-dbcommand-updateUser-field.yaml
- source/includes/apiargs-method-db.createUser-user-doc-param.yaml
- source/includes/apiargs-method-db.updateUser-update-fields.yaml
- source/includes/fact-auth-restrictions-array-contents.rst
- source/includes/fact-roles-array-contents.rst
- source/reference/command/createUser.txt
- source/reference/command/updateUser.txt
- source/reference/method/db.createUser.txt
- source/reference/method/db.updateUser.txt
Documenting the new field for createUser and updateUser
Code review: https://mongodbcr.appspot.com/158820001/
Staging: 
https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-10569/reference/method/db.createUser.html
https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-10569/reference/method/db.updateUser.html
https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-10569/reference/command/createUser.html
https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-10569/reference/command/updateUser.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2986)
> DOCS-10569 - Adding authentication restrictions for createUser and updateUser

- source/includes/fact-tcp-keepalive-windows.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2993)
> DOCS-10337: Include /t REG_DWORD to set correct registry value type for KeepAliveTime on Windows

- source/reference/operator/aggregation/bucketAuto.txt
Added a paragraph describing the effects of cardinality on $bucketAuto.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3005)
> DOCSP-1173 Updated according to reviewer's suggestions.

- source/includes/options-conf.yaml
- source/reference/configuration-options.txt
- source/reference/log-messages.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3020)
> DOCS-9988 - Document new replication heartbeats log component.

- source/administration/production-checklist-operations.txt
- source/administration/production-notes.txt
- adjust wording per https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-tcp-idle-timeout
- link Production Checklist directly to production notes on Azure instead of ecosystem => production notes
- add note that `mongod`/`mongos` restart is required after changing `tcp_keep_alive`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3035)
> DOCS-9751: Regarding the TCP keepalive setting on Azure

- source/core/index-creation.txt
- source/includes/fact-index-build-default-memory-limit.rst
- source/includes/fact-index-build-memory-limit.rst
- source/reference/command/createIndexes.txt
- source/reference/limits.txt
- source/reference/parameters.txt
https://mongodbcr.appspot.com/169250002/
For both 3.4 and 3.6 manuals
No release notes for this one, since it's all 3.4 material.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3054)
> DOCS-9454: Limit total memory utilization for bulk index builds

- source/includes/steps-getting-started.yaml
- source/tutorial/getting-started.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3079)
> Getting Started to use drivers tab set

- source/reference/method/db.collection.dropIndex.txt
- source/reference/method/db.collection.dropIndexes.txt
Added the same warning as the `dropIndexes` command page: https://docs.mongodb.com/manual/reference/command/dropIndexes/#dbcmd.dropIndexes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3076)
> DOCS-5715: Add warning on lock scope for dropIndexes shell helpers

- source/core/security-ldap-external.txt
- fix duplicate 'the' (line 275)
- clean whitespace
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3077)
> DOCS-10984 Fix duplicate 'the'

- source/includes/fact-timeZoneInfo.rst
- source/includes/options-conf.yaml
- source/includes/options-mongod.yaml
- source/includes/options-mongos.yaml
- source/reference/program/mongos.txt
- source/release-notes/3.6.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3082)
> DOCS-10881 add info about time zone options

- source/index.txt
@kay-kim if this looks good, we will need to publish to 3.6 and 3.4 branches. 
I switched the order of what I think was original (docs first, then a link to the product). If you prefer the other way around I can do that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3085)
> DOCSP-1327: Fix Stitch admonition

- source/faq/storage.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3087)
> DOCS-10720 Clarify 'file bytes available for reuse' in  WT FAQ

- source/tutorial/change-oplog-size.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3091)
> DOCS-10808 fix oplog resize instructions on mmap

- config/redirects
- source/includes/apiargs-method-db.collection.createIndex-options-param.yaml
- source/includes/apiargs-method-db.collection.createIndexes-option-collation.yaml
- source/includes/apiargs-method-db.collection.createIndexes-options-2d.yaml
- source/includes/apiargs-method-db.collection.createIndexes-options-2dsphere.yaml
- source/includes/apiargs-method-db.collection.createIndexes-options-geohaystack.yaml
- source/includes/apiargs-method-db.collection.createIndexes-options-param.yaml
- source/includes/apiargs-method-db.collection.createIndexes-options-text.yaml
- source/includes/apiargs-method-db.collection.createIndexes-param.yaml
- source/includes/extracts-collation.yaml
- source/includes/extracts-createIndex-behavior.yaml
- source/includes/fact-index-key-length-operation-behaviors.rst
- source/includes/ref-toc-method-collection.yaml
- source/reference/method/db.collection.createIndex.txt
- source/reference/method/db.collection.createIndexes.txt
For v3.2, v3.4, and master -- sorry! It should merge nicely, though, I think.
First time doing new format of redirects, so please double-check that I've not messed that up 😁 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3090)
> DOCS-9003: adds method ref for db.collection.createIndexes()

- source/includes/steps-run-mongodb-on-windows.yaml
Small typo fix, but this exists as far back as 3.2. Might be worth backporting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3092)
> DOCS-10999: Typo in windows installation tutorial

- source/includes/fact-iso-date-objects.rst
- source/reference/operator/aggregation/dateToParts.txt
- source/reference/operator/aggregation/dateToString.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3095)
> DOCS-10404 date expressions may include ObjectID

- source/reference/built-in-roles.txt
- source/reference/command/createUser.txt
- source/reference/privilege-actions.txt
Code review: https://mongodbcr.appspot.com/171210001/
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-10904/reference/privilege-actions.html#database-management-actions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3097)
> DOCS-10904 - Documenting new action type for auth restrictions

- source/core/capped-collections.txt
- source/faq/concurrency.txt
- source/includes/fact-database-lock.rst
- source/reference/command/cloneCollectionAsCapped.txt
- source/reference/command/convertToCapped.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3102)
> DOCS-10992 capped commands take DB_X locks

- source/tutorial/configure-a-non-voting-replica-set-member.txt
The use of letter 'an' is not grammatically correct here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3112)
> Typo on configure-a-non-voting-replica-set-member.txt

- source/tutorial/configure-a-hidden-replica-set-member.txt
The use of letter 'a' is not grammatically correct here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3113)
> Typo on configure-a-hidden-replica-set-member.txt

- source/reference/parameters.txt
- source/release-notes/3.6.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3114)
> DOCS-11038: waitForSecondaryBeforeNoopWriteMS parameter

- source/includes/options-mongo.yaml
- source/reference/connection-string.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3124)
> Docs 10980

- source/includes/apiargs-pipeline-bucket-field.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3122)
> DOCS-10156 - Clarified the statement about the default bucket value

- source/core/security-ldap-external.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3105)
> Move security.ldap.bind fixes

- source/includes/extracts-manage-journaling.yaml
- source/includes/options-mongod.yaml
- source/includes/warning-disable-journaling.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3126)
> DOCS-10928: --nojournal option warning for manual v3.4

- source/reference/command/isMaster.txt
[Code Review](https://mongodbcr.appspot.com/171660001/)
[Staged Version](https://docs-mongodbcom-staging.corp.mongodb.com/nick/DOCS-10676/reference/command/isMaster.html#isMaster.logicalSessionTimeoutMinutes)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3107)
> DOCS-10676: isMaster returns logicalSessionTimeoutMinutes

- source/includes/ref-toc-method-plan-cache.yaml
- source/reference/command/planCacheListPlans.txt
- source/reference/method/PlanCache.getPlansByQuery.txt
- source/release-notes/3.6.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3128)
> DOCS-11025: added a timestamp to plan cache entries

- source/includes/fact-install-windows.rst
- source/installation.txt
- source/reference/program.txt
- source/reference/program/install_compass.txt
- source/release-notes/3.6.txt
- source/tutorial/install-mongodb-enterprise-on-windows.txt
Code review: https://mongodbcr.appspot.com/173770002/
Staging: 
https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-10906/installation.html
https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-10906/tutorial/install-mongodb-on-windows.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3130)
> DOCS-10906 - Add Compass Installer to MongoDB packaging

- source/administration/change-streams-production-recommendations.txt
- source/includes/fact-cannot-resume-invalidated-change-stream.rst
- source/reference/change-events.txt
- source/tutorial/change-streams-example.txt
[Code Review](https://mongodbcr.appspot.com/172690001/)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/nick/DOCS-10668/reference/change-events.html#invalidate-event)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3142)
> DOCS-10668: Change stream invalidate events

- source/reference/command/compact.txt
Note: also fixes the `compact` part of DOCS-9267: WiredTiger Space Requirements & Behavior during repair and compact
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3143)
> DOCS-9714 Clarify operation of compact command with WiredTiger

- source/reference/parameters.txt
- source/release-notes/3.6.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3144)
> DOCS-10448: KeysRotationIntervalSec server parameter

- source/includes/options-conf.yaml
- source/reference/configuration-options.txt
- source/reference/log-messages.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3139)
> DOCS-10653 - Document replication rollback log component.

- source/includes/fact-json-schema-validation-keywords.rst
- source/tutorial/change-streams-example.txt
There's one for JSON Schema and one for change streams.
I noticed the missing change streams link at the bottom of this page: https://docs.mongodb.com/manual/changeStreams/. Someone on the docs team might want to double-check, since my laptop is no longer set up for docs builds and I can't test it :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3150)
> Typos in some new 3.6 feature pages

- source/includes/steps-configure-ldap-mongodb.yaml
Small change to add a CLI Auth example to this tutorial. Functionality tested and confirmed.
[Jira Ticket](https://jira.mongodb.org/browse/DOCS-10018)
[Staged Changes](https://docs-mongodbcom-staging.corp.mongodb.com/nick/DOCS-11018/tutorial/configure-ldap-sasl-openldap.html#authenticate-the-user-in-the-mongo-shell)
[Code Review](https://mongodbcr.appspot.com/170900002/)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3155)
> DOCS-10018: CLI auth in OpenLDAP Tutorial

- source/includes/steps-install-mongodb-on-osx-with-homebrew.yaml
There is no available option `--with-openssl` . This is installed by default. Adding this option gives the user a warning during install.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3158)
> Took out --with-openssl option b/c doesn't exist

- source/reference/command/isMaster.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3162)
> DOCS-11045: adds new isMaster output fields for cluster time

- source/includes/steps-configure-windows-service-for-mongodb.yaml
- source/includes/steps-create-manually-windows-service-for-mongodb.yaml
- source/includes/steps-run-mongodb-on-debian.yaml
- source/includes/steps-run-mongodb-on-linux.yaml
- source/includes/steps-run-mongodb-on-windows.yaml
- All tutorials include 'Verify MongoDB started successfully' step
- All tutorials ensure user attempts to connect successfully to the mongod
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3169)
> DOCS-11126: Improvements to Installation Tutorials

- source/reference/command/setParameter.txt
- source/reference/parameters.txt
Also fix two minor typos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3157)
> DOCS-8981: Document maxLogSizeKB parameter

- source/tutorial/configure-a-non-voting-replica-set-member.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3178)
> DOCSP-1494: members can have 0 or 1 votes, not more

- source/reference/command/repairDatabase.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3147)
> DOCS-9267 WT space requirements for repairDatabase

- source/reference/read-concern.txt
That sentence still makes me sad, but we shall persevere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3180)
> DOCS-11128: rephrase afterClusterTime reference in read concern docs

- source/core/replica-set-oplog.txt
- source/reference/command/replSetResizeOplog.txt
- source/tutorial/change-oplog-size.txt
Staged:
- https://docs-mongodbcom-staging.corp.mongodb.com/rkumar/DOCS-11134/reference/command/replSetResizeOplog.html#dbcmd.replSetResizeOplog
- https://docs-mongodbcom-staging.corp.mongodb.com/rkumar/DOCS-11134/tutorial/change-oplog-size.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3176)
> DOCS-11134: Update oplog resize tutorial to use replSetResizeOplog

- config/build_conf.yaml
- source/includes/changelogs/releases/3.6.1.rst
- source/release-notes/3.6.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3182)
> DOCS-11133 3.6.1

- source/includes/steps-configure-windows-service-for-mongodb.yaml
- source/tutorial/install-mongodb-on-windows.txt
The installation steps for 3.6 still have references to 3.4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3181)
> DCoupal patch - 3.6 install windows

- source/includes/extracts-fact-query-bitwise.yaml
- source/reference/operator/query/bitsAllClear.txt
- source/reference/operator/query/bitsAllSet.txt
- source/reference/operator/query/bitsAnyClear.txt
- source/reference/operator/query/bitsAnySet.txt
Also some copy fixes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3183)
> DOCS-11140: bitwise query operations can't use indexes

- source/reference/method/db.auth.txt
One cannot authenticate into the MongoDB shell ( at least in version 3.6.0 ) w/o specifying the authentication database. Following the format of the other flags mentioned here, one can use the --authenticationDatabase flag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3187)
> Update db.auth.txt w/ needed shell flag

- Makefile
- source/includes/fact-default-bind-ip.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3195)
> Fix Java sync example URL and add link to --bind_ip on compatibility page.

- source/reference/command/compact.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3196)
> DOCS-8986 clarify compact with MMAPv1 and WiredTiger

- source/tutorial/query-documents.txt
Adding a blurb to the Compass tab for Query Documents page stating that Compass autocompletes queries. Will be adding a more detailed example to the Compass docs.
Code review: https://mongodbcr.appspot.com/178390001/
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCSP-1604/tutorial/query-documents.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3193)
> DOCSP-1604 - Documenting autocomplete for Compass query bar

- source/reference/program/install_compass.txt
Documenting improvements to the installation experience for install_compass.
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-11200/reference/program/install_compass.html
Code review: https://mongodbcr.appspot.com/175980001/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3203)
> DOCS-11200 - Updating install_compass install docs for Linux and Mac

- source/tutorial/manage-the-database-profiler.txt
`sampleRate` is global, just as `slowms` so changing the wording to make it clear.  Sorry if I screwed up formatting, feel free to fix up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3206)
> sampleRate is global

- source/includes/options-mongostat.yaml
- source/reference/program/mongostat.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3164)
> DOCS-10953: adds --interactive option to mongostat reference

- source/reference/parameters.txt
I often forget the syntax of having a document value for setParameter on the command line.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3212)
> add example of logComponentVerbosity cmdline

- source/reference/operator/query/where.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3210)
> DOCS-11142: prefer $expr over $where

- source/includes/steps-deploy-replica-set-with-auth.yaml
- source/tutorial/enable-authentication.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3217)
> DOCS-8249: deploy repl with auth

- source/tutorial/manage-sharded-cluster-balancer.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3215)
> DOCS-11227: use balancerStart/Stop command to start/stop balancer

- source/includes/apiargs-dbcommand-listCollections-field.yaml
- source/includes/apiargs-method-db.getCollectionInfos-param.yaml
- source/reference/method/db.getCollectionInfos.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3214)
> DOCS-8977: include filter param for db.getCollectionInfos()

- source/includes/apiargs-dbcommand-shardCollection-field.yaml
- source/reference/command/shardCollection.txt
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-10671/reference/command/shardCollection.html
Code review: https://mongodbcr.appspot.com/184410001/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3216)
> DOCS-10671 - Expand key description for shardCollection command

- source/includes/note-distinct-bson-limit-agg-alternative.rst
- source/includes/table-sql-to-mongo-select-examples.yaml
- source/reference/command/distinct.txt
- source/reference/method/db.collection.distinct.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3213)
> DOCS-9120: emphasize BSON limit on distinct, propose agg alternative

- source/tutorial/troubleshoot-replica-sets.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3218)
> Docsp 6564

- source/core/sharded-cluster-components.txt
My 72 character line wrap altered some text unintentionally. My apologies for any confusion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3204)
> change language around sharded clusters and mongos configs

- source/release-notes/3.6-compatibility.txt
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-11241/release-notes/3.6-compatibility.html#array-operation-compatibility-changes
Code review: https://mongodbcr.appspot.com/179890001/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3219)
> DOCS-11241 - Updating compatibility notes for sorting on multiple array fields

- source/tutorial/deploy-shard-cluster.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3221)
> DOCS-10874 Mention replica set names requirement

- source/core/sharded-cluster-query-router.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3222)
> DOCS-7237 adding changes to sharded merge in 3.6

- source/reference/server-sessions.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3230)
> fix articles

- source/tutorial/change-streams-example.txt
var name change -- was incorrect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3242)
> DOCSP-1910: fixed typo in java example

- source/includes/options-mongodump.yaml
- source/includes/options-mongoexport.yaml
- source/includes/options-mongofiles.yaml
- source/includes/options-mongoimport.yaml
- source/includes/options-mongorestore.yaml
- source/includes/options-mongostat.yaml
- source/includes/options-mongotop.yaml
- source/includes/options-shared.yaml
- source/reference/program/mongodump.txt
- source/reference/program/mongoexport.txt
- source/reference/program/mongofiles.txt
- source/reference/program/mongoimport.txt
- source/reference/program/mongorestore.txt
- source/reference/program/mongostat.txt
- source/reference/program/mongotop.txt
Code review: https://mongodbcr.appspot.com/177950001/
Updated pages in staging:
https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCSP-1018/reference/program/mongotop.html
https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCSP-1018/reference/program/mongostat.html
https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCSP-1018/reference/program/mongoimport.html
https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCSP-1018/reference/program/mongoexport.html
https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCSP-1018/reference/program/mongorestore.html
https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCSP-1018/reference/program/mongodump.html
https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCSP-1018/refer …
> DOCSP-1018 - Documenting --uri option for tools

- source/core/index-partial.txt
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-8848/core/index-partial.html
Code review: https://mongodbcr.appspot.com/188290001
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3236)
> DOCS-8848 - Updating partial index example

- source/reference/exit-codes.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3225)
> DOCS-11286: missing mongod exit code 62

- source/includes/options-mongorestore.yaml
- source/reference/program/mongorestore.txt
For 3.4 and master, please.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3244)
> DOCP-980 correct oplogReplay behaviour for 3.4+

- config/redirects
- source/includes/ref-toc-method-sh.yaml
- source/reference/method/sh.disableAutoSplit.txt
- source/reference/method/sh.enableAutoSplit.txt
`99aebf6` should please be back-ported to v3.4.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3243)
> DOCS-9807: adds docs for sh.enableAutoSplit and sh.disableAutoSplit

- source/includes/apiargs-command-mapReduce-field.yaml
If you were feeling generous, you could plop this into 3.4 as well :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3245)
> DOCS-11265: clarify default for mapReduce verbose option

- source/core/index-multikey.txt
- source/includes/fact-multikey-index-sort-limitation.rst
- source/release-notes/3.6-compatibility.txt
- source/tutorial/sort-results-with-indexes.txt
Code review: https://mongodbcr.appspot.com/189350001/
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-11338/core/index-multikey.html
https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-11338/tutorial/sort-results-with-indexes.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3246)
> DOCS-11338 - Add multikey index sort limitation to tutorial and manual pages

- source/administration/production-notes.txt
@steveren : This includes two short adds: [AWS EC2 settings](https://docs-mongodbcom-staging.corp.mongodb.com/anthonysansone/DOCSP-1271/administration/production-notes.html#aws-ec2) and [swappiness](https://docs-mongodbcom-staging.corp.mongodb.com/anthonysansone/DOCSP-1271/administration/production-notes.html#set-vm-swappiness-at-least-1)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3233)
> (DOCSP-1271, DOCS-10405): Updated Production Notes.

- source/administration/production-checklist-operations.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3260)
> DOCS-6174 Add vm.max_map_count recommendation to Production Checklist

- source/includes/fact-auth-restrictions-array-contents.rst
- source/includes/fact-cleartext-passwords-tls.rst
- source/reference/command/createUser.txt
- source/reference/command/updateUser.txt
- source/reference/method/db.changeUserPassword.txt
- source/reference/method/db.createUser.txt
- source/reference/method/db.updateUser.txt
@kay-kim RFM into master. Would need to remove the chunk on authrestrictions if we want to backport to 3.2/3.4.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3258)
> DOCS-11415: Use TLS to mitigate cleartext passwords

- source/includes/extracts-concurrency-consistency-recency.yaml
- source/reference/read-concern.txt
@kay-kim RFM for master and 3.4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3264)
> DOCS-11447: Improve docs on linearizable read concern

- source/reference/command/flushRouterConfig.txt
@steveren , @kaloianm : This PR adds the invocation example and changes the explanation as to how the cache is cleared and rebuilt. [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/anthonysansone/DOCS-10826/reference/command/flushRouterConfig.html)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3262)
> (DOCS-9990, -10826): Updated flushRouterConfig.

- source/includes/apiargs-dbcommand-usersInfo-field.yaml
- source/includes/apiargs-method-db.getUser-field.yaml
- source/reference/command/usersInfo.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3268)
> DOCS-11433 Add showAuthenticationRestrictions parameter

- source/includes/apiargs-dbcommand-fsync-field.yaml
- source/includes/ref-toc-command-administration.yaml
- source/includes/steps-backup-sharded-cluster-with-snapshots.yaml
- source/includes/steps-backup-sharded-clusters-dumps.yaml
- source/reference/command/fsync.txt
- source/reference/command/fsyncUnlock.txt
- source/reference/method/db.fsyncLock.txt
- source/reference/method/db.fsyncUnlock.txt
- source/tutorial/backup-with-filesystem-snapshots.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3274)
> DOCS-9265, DOCS-5976: fsyncLock/Unlock and lock counts

- source/includes/extracts-production-notes-base.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3279)
> Sgb docsp 2098

- config/sphinx_local.yaml
- source/images/read-concern-write-timeline.svg
- source/includes/fact-read-concern-write-timeline.rst
- source/includes/fact-readConcern-syntax.rst
- source/reference/read-concern-available.txt
- source/reference/read-concern-linearizable.txt
- source/reference/read-concern-local.txt
- source/reference/read-concern-majority.txt
- source/reference/read-concern.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3281)
> reorg of read concern (for merge on Monday)

- source/reference/command/serverStatus.txt
- source/release-notes/4.0-compatibility.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3291)
> DOCS-11248: asserts.wranings = 0

- source/reference/ulimit.txt
Backport to 3.2 and 3.4.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3251)
> DOCS-10721 Document locked memory ulimit

- source/core/security-internal-authentication.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3256)
> DOCS-11421 Internal auth is used by mongos

- source/includes/apiargs-method-cursor.tailable-param.yaml
- source/reference/method/cursor.tailable.txt
Backport to 3.6 (and 3.4 if one is feeling charitable) would be lovely :D
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3303)
> DOCSP-2294: correct param name for cursor.tailable method

- source/includes/steps-configure-windows-service-for-mongodb.yaml
- source/includes/steps-create-manually-windows-service-for-mongodb.yaml
@kay-kim : This builds on the DOCS-11026 already in RFM. RFM for `v3.6` and `master`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3329)
> (DOCS-10248): Fixed command prompt listings.

- source/includes/access-mongorestore-collections.rst
@rob-mongodb : This is a small update to the permission grants needed to run `mongorestore`. [Staged.](https://docs-mongodbcom-staging.corp.mongodb.com/anthonysansone/DOCS-11010/tutorial/backup-and-restore-tools.html#access-control)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3332)
> (DOCS-11010): Update mongorestore grants.

- source/includes/apiargs-method-db.collection.explain-param.yaml
- source/includes/extracts-wired-tiger.yaml
- source/reference/method/db.collection.explain.txt
Quick fixes from docs triage
([staged changes](https://docs-mongodbcom-staging.corp.mongodb.com/nick/triage/reference/configuration-options.html#storage.wiredTiger.engineConfig.cacheSizeGB)) [DOCS-11776: Provide example(s) of WiredTiger cacheSizeGB default calculation](https://jira.mongodb.org/browse/DOCS-11776)
([staged changes](https://docs-mongodbcom-staging.corp.mongodb.com/nick/triage/reference/method/db.collection.explain.html#db.collection.explain)) [DOCS-11777: db.collection.explain("verbosity") now supported for aggregation](https://jira.mongodb.org/browse/DOCS-11777)
_**Please backport DOCS-11777 to 3.6**_
> Triage Updates

- source/tutorial/install-mongodb-on-windows.txt
@rob-mongodb : This updates the [System Requirements](https://docs-mongodbcom-staging.corp.mongodb.com/anthonysansone/DOCS-10466/tutorial/install-mongodb-on-windows.html#system-requirements) for the MongoDB Community install on Windows. A sanity check would be appreciated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3330)
> (DOCS-10466, -10467, -11485): Updated System Requirements for Community Windows install.

- source/includes/note-clean-shutdown.rst
- source/includes/steps-3.6-downgrade-mongod.yaml
- source/includes/steps-3.6-downgrade-replica-set.yaml
- source/includes/steps-3.6-downgrade-sharded-cluster.yaml
@MongoCaleb : There are a few line wrap issues, but the big thing is the note that I added:
- [Standalone](https://docs-mongodbcom-staging.corp.mongodb.com/anthonysansone/DOCS-11711/release-notes/3.6-downgrade-standalone.html#restart-with-the-latest-oldversion-mongod-instance)
- [Replica Set](https://docs-mongodbcom-staging.corp.mongodb.com/anthonysansone/DOCS-11711/release-notes/3.6-downgrade-replica-set.html#downgrade-secondary-members-of-the-replica-set)
- [Sharded Cluster](https://docs-mongodbcom-staging.corp.mongodb.com/anthonysansone/DOCS-11711/release-notes/3.6-downgrade-sharded-cluster.html#downgrade-each-shard-one-at-a-time)
Staging build is still ongoing. Stage may not reflect code.
> (DOCS-11711): Updated downgrade shutdown requirement.

- source/installation.txt
- source/tutorial/install-mongodb-on-windows.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3331)
> (DOCS-10465): Include blurb on different MongoDB editions

- source/administration/production-checklist-operations.txt
@kay-kim : This is a short update for the NTFS default allocation unit size. RFM for `master` and `v3.6`.
> (DOCS-6329): Updated default NTFS allocation unit size.

- source/tutorial/install-mongodb-on-windows.txt
@rkumar-mongo : I embellished the caution about including the proper system updates. [Staged.](https://docs-mongodbcom-staging.corp.mongodb.com/anthonysansone/DOCS-11766/tutorial/install-mongodb-on-windows.html#system-requirements)
> (DOCS-11766): Add note on system updates for Windows.

- source/tutorial/install-mongodb-on-windows.txt
@rkumar-mongo : This is a simple note that tells users to make sure to turn off "Hide Known File Extensions."
> (DOCS-10422): Added information on file extension visibility.

- source/core/workload-isolation.txt
> Duplicated bullet for zones

- source/includes/extracts-install-past-mongodb.yaml
- source/includes/fact-default-bind-ip-change.rst
- source/includes/fact-install-windows-prereq.rst
- source/includes/fact-install-windows.rst
- source/includes/release-base.yaml
- source/includes/release-specifications.yaml
- source/includes/steps-configure-windows-service-for-mongodb.yaml
- source/includes/steps-create-manually-windows-service-for-mongodb.yaml
- source/includes/steps-install-mongodb-enterprise-on-windows-unattended.yaml
- source/includes/steps-install-mongodb-on-windows-enterprise-interactive.yaml
- source/includes/steps-install-mongodb-on-windows-interactive.yaml
- source/includes/steps-install-mongodb-on-windows-unattended.yaml
- source/includes/steps-run-mongodb-on-linux.yaml
- source/includes/steps-run-mongodb-on-windows.yaml
- source/tutorial/install-mongodb-enterprise-on-windows.txt
- source/tutorial/install-mongodb-on-windows.txt
@steveren : This is a total refactor.
- [Enterprise](https://docs-mongodbcom-staging.corp.mongodb.com/anthonysansone/DOCS-10468/tutorial/install-mongodb-enterprise-on-windows.html)
- [Community](https://docs-mongodbcom-staging.corp.mongodb.com/anthonysansone/DOCS-10468/tutorial/install-mongodb-on-windows.html)
> (DOCS-10468): Revised Windows Install for MongoDB

- source/reference/built-in-roles.txt
- source/reference/command/killCursors.txt
- source/reference/privilege-actions.txt
- source/release-notes/4.0-compatibility.txt
I'm not sure if the added privilege action item belongs in the compatibility notes or the main release notes, but I figured I'd put it in compatibility for now?
This change was backported to 3.6; making a separate PR for that patch.
> DOCS-11101: add killAnyCursor privilege, clarify coAuthz behaviour

- source/includes/steps-install-verify-files-windows.yaml
- source/tutorial/verify-mongodb-packages.txt
@jdestefano-mongo : This adds information to verify a Windows MongoDB installer binary. [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/anthonysansone/DOCSP-10909/tutorial/verify-mongodb-packages.html#verify-windows-packages)
@markbenvenuto : Your review would also be appreciated.
> (DOCS-10909): Added verification for Windows build.

- source/release-notes/4.0-compatibility.txt
aggregation with $out cannot span db's so it's not relevant here
> removing incorrect suggestion

- source/includes/apiargs-dbcommand-listCollections-field.yaml
- source/reference/command/listCollections.txt
[Staged Change](https://docs-mongodbcom-staging.corp.mongodb.com/nick/DOCS-11858/reference/command/listCollections.html#dbcmd.listCollections)
[DOCS-11858](https://jira.mongodb.org/browse/DOCS-11858)
[SERVER-35922](https://jira.mongodb.org/browse/SERVER-35922)
> (DOCS-11858): filter + nameOnly in listCollections dbcommand

- source/core/index-text.txt
The old values appears to be copypasta from the geospatial index section.
> Fix reference to textIndexVersion

- source/includes/fact-platform-x86_64.rst
- source/includes/steps-install-mongodb-enterprise-on-ubuntu.yaml
- source/includes/steps-install-mongodb-on-ubuntu.yaml
- source/release-notes/4.0.txt
This reverts commit 2b19c8f8c3e7082a7db7255d9e81c7a4fbfa9ec7.
Should merge when 4.0.1 goes live -- also shoud re-add ubuntu 18.04 to production notes
> Revert "revert for ubuntu 18.04"  ( v4.0.1 release)

- source/includes/list-table-featureCompatibilityVersion-defaults.rst
Saw it on [this page](https://docs.mongodb.com/manual/reference/command/setFeatureCompatibilityVersion/).
> minor: fix featureCompatibilityVersion typo

- source/tutorial/change-oplog-size.txt
I realize this page is written in an old style (for example, it doesn't have the fancy numbering system that [this page](https://docs.mongodb.com/manual/tutorial/perform-maintence-on-replica-set-members/) has) but the typos annoyed me.
> minor: fix typos in oplog resizing tutorial

- source/includes/fact-ObjectId-construct.rst
@kay-kim : Simple update to the definition of an ObjectID. RFM for `master`, `v4.0`, and `v3.6`.
> (DOCS-11844): Updated ObjectID description.

- conf.py
- source/core/auditing.txt
- source/includes/note-audit-in-enterprise-only.rst
- source/reference/audit-message.txt
- source/tutorial/configure-audit-filters.txt
- source/tutorial/configure-auditing.txt
Staged:
https://docs-mongodbcom-staging.corp.mongodb.com/rkumar/DOCSP-3338/core/auditing.html
Goals: Clarify that Auditing is available on both MongoDB Atlas and in MongoDB Enterprise
Non-Goals: Updating pages for other security features in both Enterprise and Atlas.
> DOCSP-3338: Clarify Auditing Availability in Enterprise + Atlas

- source/reference/parameters.txt
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/steverenaker/DOCS-11661/reference/parameters.html#param.failIndexKeyTooLong
> DOCS-11661: Add a warning to discourage people from setting failIndexKeyTooLong

- source/reference/method/db.collection.findOneAndUpdate.txt
Changing header level of "Examples", to be visible in On this page section
> Missing examples label in "On this page" section

- source/reference/operator/aggregation/toBool.txt
- source/reference/operator/aggregation/toDate.txt
- source/reference/operator/aggregation/toDecimal.txt
- source/reference/operator/aggregation/toDouble.txt
- source/reference/operator/aggregation/toInt.txt
- source/reference/operator/aggregation/toLong.txt
- source/reference/operator/aggregation/toString.txt
Remove the redundant 'of' in the description of the other shorthand type conversion operators.
> Remove redundant 'of' in type conversion operators.

- source/changeStreams.txt
- source/includes/extracts-changestream.yaml
- source/reference/method/db.collection.watch.txt
- source/reference/privilege-actions.txt
Included some revisions based on comments in CR. Will forward port to 4.0 and master after this is approved/merged.
> DOCS-12098: Clarify change stream permissions, document changeStream privilege action

- source/reference/operator/aggregation/count.txt
Re: https://github.com/Automattic/mongoose/issues/7114, the current description is misleading because it implies that if `$count` is the last aggregation stage, you should get a single document as output rather than a cursor or array.
Also, it looks like all the links on https://github.com/mongodb/docs/blob/master/CONTRIBUTING.rst are broken, like [this one](https://docs.mongodb.com/manual/meta/style-guide), so my apologies if this doesn't conform to a style guideline or convention.
> Improve description of aggregation `$count`

- source/includes/fact-json-schema-validation-keywords.rst
Changes `MongoBD` -> `MongoDB`
> Fix Typo in $jsonSchema keywords table

- source/reference/method/Session.commitTransaction.txt
This is consistent with the language in the [command reference](https://github.com/mongodb/docs/blob/master/source/reference/command/commitTransaction.txt). See also: https://english.stackexchange.com/a/22075
> Use plural verb for "none"

- source/core/gridfs.txt
- source/includes/extracts-built-in-roles.yaml
- source/reference/command/setFeatureCompatibilityVersion.txt
- source/reference/operator/aggregation/cond.txt
- source/reference/operator/query/and.txt
DOCS-12567: Removing duplicate line
DOCSP-4943: $cond requires all arguments
DOCS-12556: Deprecate GridFS contentType, aliases, MD5
DOCS-12543: query $and accepts one expression
DOCSP-4791: Certain background operations can block setFeatureCompatibilityVersion
@kay-kim LMK if I've done something insidious among these minor fixes! No rush.
> Multiple small fixups:

- source/tutorial/analyze-query-plan.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3270)
> grammar tweak

- source/reference/operator/update/addToSet.txt
https://docs.mongodb.com/manual/reference/operator/update/addToSet/#field-is-not-an-array
> docs($addToSet): use a simple example update for `Field is Not an Array`

- source/reference/method/db.collection.findOneAndUpdate.txt
I just found a typo in the `findOneAndUpdate` method. 
It's a rather small fix, so hopefully it is okay :-)
> fixes typo; referencing MacDyver in findOneAndUpdate method

- source/applications/indexes.txt
Fixes the grammatical error in `...frequent queries on large data set.`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3148)
> docs(indexes): fix grammatical error

- source/reference/operator/aggregation/abs.txt
Hi Docs Team!
The `$abs` page has a duplicate paragraph that discusses the result if the input is `null` or `NaN`, one of which comes from the extract and one of which is verbatim in the text. This pull request proposes deleting the text in the `$abs` page and keeps the extract.
Hope you're all well!
Kyle
> Delete duplicate paragraph about $abs and null/NaN

- source/meta/aggregation-quick-reference.txt
Hope I haven't screwed up the link format (.rst is much weirder to me than Markdown :). Wanted to link to https://docs.mongodb.com/manual/core/document/#document-dot-notation. And sorry for [the big diff, all subsequent lines are due only to my trying to preserve wrapping](https://softwareengineering.stackexchange.com/questions/351549/style-line-length-and-wrapping-of-comments-in-javascript).
> Typo fix and link to the dot notation

- source/reference/connection-string.txt
Remove a redundant close bracket in standard URI connection scheme
> Update connection-string.txt to fix URI scheme typo

- source/includes/extracts-4.0-errata.yaml
The bug was fixed in 10.14.1, so I changed "10.13+" to specify just the 10.12 and 10.13 versions.  10.14.0 is also affected but I think we assume that users must keep up with operating system minor upgrades.
> Update macOS bug warning

- source/reference/security-client-side-automatic-json-schema.txt
UUID equivalent of a base64-encoded id in the JSON Schema was missing closing quote
> CSFLE Json Schema - added missing quote

- source/reference/operator/aggregation/ne.txt
$ne (aggregation) is refering to /includes/extracts/fact-agg-comparison-expression-lte.rst
instead of fact-agg-comparison-expression-ne.rst
> (Typo fix) $ne (aggregation) refering lte comparison

- source/reference/database-references.txt
Clarify supported / not supported in separate column, and provide links directly to ecosystem for driver options that do support DBRefs
> DOCSP-6837 Refactor drivers table to lean on ecosystem

- source/reference/program/mongo.txt
Updated examples to include platform-specific quoting instructions, and clarified language otherwise.
> DOCS-12940 add Windows-specific quoting for --eval

- source/reference/parameters.txt
Corrected minor typo on watchdogPeriodSeconds.
(no backporting required)
> DOCSP-6950 corrected typo on 'watchdogPeriodSeconds'

- source/reference/connection-string.txt
Included prominent write concern URI connection string example, and changed extant write concern w:2 example to majority per recommended usage guidance.
> DOCSP-5677 Add write concern URI + operator examples

- source/includes/note-killSessions.rst
- source/reference/command/killAllSessions.txt
- source/reference/command/killAllSessionsByPattern.txt
- source/reference/command/killSessions.txt
Specifically, that any ops and cursors in the session will be killed - but the session itself may remain, and might continue to be listed and used as normal by subsequent operations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3254)
> Clarify what killing a session means.

- config/redirects
Added pre-4.0 redirects to atomicity page for non-existent pages.
Will require backports to 3.6, 3.4, and 3.2.
> added pre v4.0 redirects to atomocity page to avoid 404s

- source/includes/steps-change-replica-set-wiredtiger.yaml
- source/includes/steps-change-standalone-wiredtiger.yaml
- source/release-notes/4.2-compatibility.txt
- source/release-notes/4.2-upgrade-replica-set.txt
- source/release-notes/4.2-upgrade-sharded-cluster.txt
- source/release-notes/4.2-upgrade-standalone.txt
- source/release-notes/4.2.txt
- source/tutorial/change-standalone-wiredtiger.txt
Provided messaging to advise removing MMAPv1 options from WiredTiger deployments, with prominent warnings that these options prevent WiredTiger deployments on 4.2 from starting.
> Docs 12969 mma pv1 deprecation command parameters

- source/includes/options-mongod.yaml
Expanded pidFilePath option explanation to highlight the more common use of a system's init system to handle PID and PID files, with additional clarification around matching pidFilePath with fork.
> DOCS-5696 Clarify PIDfile permissions and usage, with note

- source/reference/method/db.collection.countDocuments.txt
This is the same as #3681, except with a second commit to remove the reference to the 4.2 series. This is for the 4.0.13 branch.
Code review: https://mongodbcr.appspot.com/507280007/
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/v4.0.13/reference/method/db.collection.countDocuments.html#empty-or-non-existing-collections-and-views
>  (DOCS-12966): Updating behavior for countDocuments on empty collections 

- source/reference/method/db.collection.dropIndexes.txt
Corrected two instances of getIndexes() --> dropIndexes()
> corrected 2 instances of dropIndexes(), previously getIndexes()

- source/includes/note-suse-ulimit.rst
- source/reference/ulimit.txt
- source/tutorial/install-mongodb-enterprise-on-suse.txt
- source/tutorial/install-mongodb-on-suse.txt
Provided updated nproc conf file for `el7` (changed from `el6`).
> DOCSP-7092 clarified RHEL/CentOS nprocs override note

- config/sphinx_local.yaml
- source/tutorial/install-mongodb-enterprise-on-amazon-tarball.txt
- source/tutorial/install-mongodb-enterprise-on-amazon.txt
Split the tarball installation to its own page. Moved Packages section to the bottom under Additional Info.
https://docs-mongodbcom-staging.corp.mongodb.com/docsworker-xlarge/install-improvements/tutorial/install-mongodb-enterprise-on-amazon.html
> (DOCSP-7259): Standardizing amazon enterprise install page

- source/includes/note-suse-ulimit.rst
Updated language to include cases where mongod is started manually, not necessarily just from the TGZ.
> DOCS-10088 clarify ulimit change behavior for manual installs

- source/includes/steps-run-mongodb-on-ubuntu-tarball.yaml
- source/tutorial/install-mongodb-enterprise-on-amazon-tarball.txt
Tweaked the include file to point to the correct log file. Tested and the ubuntu instructions also work on Amazon Linux.
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/docsworker-xlarge/install-improvements/tutorial/install-mongodb-enterprise-on-amazon-tarball.html#run-mongodb
> Adding run instructions for mdb enterprise tgz on amazon

- source/core/databases-and-collections.txt
- source/reference/command/create.txt
- source/reference/command/renameCollection.txt
- source/reference/method/db.collection.renameCollection.txt
- source/reference/method/db.createCollection.txt
- source/reference/mongo-shell.txt
- source/release-notes/3.4-compatibility.txt
Provided deprecation notice for $ character beginning in 3.4, and provided links to naming restrictions doc for naming and renaming commands.
> DOCS-9518 clarify dbname and collection naming restriction

- changelogs/changelog_conf.yaml
- changelogs/generatechangelogs.py
Refactoring changelog generation procedure
To run, execute the new `generatechangelog.py` file. e.g., from the root of the `docs` directory, run: `python changelogs/generatechangelogs.py`
The program prompts you for the version to generate the changelogs. Specify the MongoDB version (e.g., `4.0.13`).
> Refactoring changelog generation procedure

- Makefile
Can now run `make changelogs` from the root of the `docs` repo.
> Adding changelogs script to makefile

- source/administration/production-notes.txt
- source/includes/extracts-install-mongodb-manually.yaml
- source/includes/fact-platform-x86_64.rst
- source/includes/note-suse-ulimit.rst
- source/includes/steps-install-mongodb-enterprise-on-suse.yaml
- source/includes/steps-install-mongodb-on-suse.yaml
- source/reference/ulimit.txt
- source/tutorial/install-mongodb-enterprise-on-suse.txt
- source/tutorial/install-mongodb-on-suse.txt
This reverts commit b21534b97e47fe941e296031551bf67cb30691d2.
> Revert "DOCS-13256 add SLES15 support"

- locale/es/LC_MESSAGES/core/ranged-sharding.po
- locale/es/LC_MESSAGES/sharding.po
- locale/es/LC_MESSAGES/tutorial/deploy-sharded-cluster-ranged-sharding.po
- locale/pot/core/ranged-sharding.pot
- locale/pot/sharding.pot
- locale/pot/tutorial/deploy-sharded-cluster-ranged-sharding.pot
- locale/zh/LC_MESSAGES/core/ranged-sharding.po
- locale/zh/LC_MESSAGES/sharding.po
- locale/zh/LC_MESSAGES/tutorial/deploy-sharded-cluster-ranged-sharding.po
- source/core/ranged-sharding.txt
- source/sharding.txt
- source/tutorial/deploy-shard-cluster.txt
I think "ranged-based sharding" is not proper English
> Use "range-based sharding" spelling

- source/core/replica-set-oplog.txt
- source/reference/command/replSetResizeOplog.txt
- source/tutorial/change-oplog-size.txt
I believe we should backport this change to v4.0
> (DOCS-12863): Forbid dropping oplog in all scenarios

- source/reference/installation-ubuntu-community-troubleshooting.txt
Using double `--` it is only valid for options in long format.
```
ubuntu@hostname:~$ cat /etc/issue
Ubuntu 18.04.4 LTS \n \l
ubuntu@host:~$ sudo ss --tulpn
ss: unrecognized option '--tulpn'
Usage: ss [ OPTIONS ]
(...)
```
Proposed fix:
```
ubuntu@hostname:~$ sudo ss -tulpn
Netid State   Recv-Q  Send-Q       Local Address:Port    Peer Address:Port                                                                                      
(...)
```
> Typo in `ss` command options

- source/reference/command/listCollections.txt
The parameter is documented below but was not present in the signature.
> add authorizedCollections parameter to the listCollections signature

- source/reference/command/compact.txt
grantRoleToUser method does not exists, the method is grantRolesToUser
> Fix typo in the documentation of Compact page

- source/reference/operator/aggregation/merge.txt
To avoid implying that writes happen in certain order
> rephrase warning

- source/reference/command/serverStatus.txt
serverStatus shows metrics for mongod as a whole, not for an individual database.
> correction to scope of metric

- source/core/security-client-side-encryption.txt
Per [this comment](https://mongodb.slack.com/archives/C0V2QUP4H/p1588358916158800) in Slack, PHP and Ruby officially support CSFLE and should be added to the supported driver table.
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/csfle-driver-support/core/security-client-side-encryption.html#driver-compatibility-table)
> adds php and ruby as csfle supported drivers

- source/reference/operator/aggregation/sum.txt
The paragraph above refers to an intentionally non-existent field $qty. This commit fixes the code so that it matches the non-existent field (rather than the real field).
> Fix typo in intentionally non-existent field

- source/reference/operator/aggregation/skip.txt
Sample code seems incorrect to me: aggregate() argument is an array
BEFORE : db.article.aggregate({ $skip : 5 });
AFTER : db.article.aggregate([{ $skip : 5 }]);
Willing to know if this ought to be ported to all version branches (and if not all, all from... which version ?).
> fix to aggregation skip example

- source/includes/fact-online-archive-callout.rst
- source/reference/program/mongodump.txt
- source/reference/program/mongoexport.txt
Using same copy from https://github.com/mongodb/docs-commandline-tools/pull/16
Staged: [mongodump](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCSP-10116-new/reference/program/mongodump.html)
[mongoexport](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCSP-10116-new/reference/program/mongoexport.html)
> (DOCSP-10116): Add Online Archive callout to mongodump/export

- source/includes/steps-create-index-compass.yaml
Hey @kay-kim, opening this PR to fix the comments you pointed out in https://github.com/mongodb/docs/commit/559f6da74008d07c1b79c2aeaf42649ef27aa46c. Would you mind taking a quick look at this before merge, then I'll backport?
Thanks and sorry for the mixups in the last merge!
> (DOCSP-10774): Fix bad refs in Compass index instructions

- source/core/sharded-cluster-query-router.txt
Removed incorrect reference to primary shard
This should be fixed in master and 4.2 and 4.0
> correcting where merging happens

- source/reference/program/mongod.txt
- source/release-notes/4.4.txt
- source/tutorial/recover-data-following-unexpected-shutdown.txt
- [JIRA](https://jira.mongodb.org/browse/DOCS-13378)
- [CR](https://mongodbcr.appspot.com/607390004/)
- Stage:
- [--repair](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCS-13378/reference/program/mongod.html#cmdoption-mongod-repair)
- [Recover a Standalone after an Unexpected Shutdown](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCS-13378/tutorial/recover-data-following-unexpected-shutdown.html)
- [Release Notes](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCS-13378/release-notes/4.4.html#mongod-repair-behavior-change)
> DOCS-13378 Change repair to only rebuild indexes on repaired collections

- source/core/security-client-side-encryption.txt
DOCS-13475: update ruby driver version to 2.12.1 for CSFLE support
> Backport DOCS-13475 to v4.2

- source/reference/program/mongod.txt
- source/release-notes/4.4.txt
[JIRA](https://jira.mongodb.org/browse/DOCS-12786)
[appspot review](https://mongodbcr.appspot.com/646070002/)
Staged
[mongod option](https://docs-mongodbcom-staging.corp.mongodb.com/zach.carr/DOCSP-12786/reference/program/mongod.html#cmdoption-mongod-ldapquerypassword)
[Release note item](https://docs-mongodbcom-staging.corp.mongodb.com/zach.carr/DOCSP-12786/release-notes/4.4.html#multiple-ldap-password-support)
> (DOCSP-12786) ldapQueryPassword setParameter accepts an array of strings in 4.4

- source/includes/extracts-transactions.yaml
I fixed a small typo (missing `a`) in the extract-transactions.yaml file `transctions` -> `transactions`
BTW I hope the PR format follow the standards, I wanted to read https://github.com/mongodb/docs/blob/master/CONTRIBUTING.rst but all links redirect to a 404)
> Fix transctions typo in extracts-transactions file

- source/reference/operator/aggregation/bucketAuto.txt
Spelling correction: then to than in source/reference/operator/aggregation/bucketAuto.txt
> Spelling correction: then to than in source/reference/operator/aggregation/bucketAuto.txt

- source/core/index-creation.txt
This reverts commit 058fe9f5d32a8e886afdb8a073e5b665a32728d8.
> Revert "DOCSP-9411 add warning re dropped indexes during replication"

- source/reference/method/cursor.skip.txt
Natural sort order is unstable so shouldn't be used in an example
> remove reference to natural

- source/core/index-creation.txt
- source/reference/command/dropIndexes.txt
- source/reference/method/db.collection.dropIndex.txt
- source/reference/method/db.collection.dropIndexes.txt
This is now in 4 places: 
https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCSP-9411-warning-for-dropping-indexes-in-some-cases-v4.2/core/index-creation.html
https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCSP-9411-warning-for-dropping-indexes-in-some-cases-v4.2/reference/command/dropIndexes.html
https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCSP-9411-warning-for-dropping-indexes-in-some-cases-v4.2/reference/method/db.collection.dropIndex.html
https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCSP-9411-warning-for-dropping-indexes-in-some-cases-v4.2/reference/method/db.collection.dropIndexes.html
> DOCSP-9411 warn about dropping indexes

- source/index.txt
In this PR, I updated the description of the drivers section to reflect its current purpose.
One question is whether you'd prefer to keep the link to "/ecosystem" which currently redirects to "/drivers" for analytics purposes or whether it is ok to update to the latter.
> update link and description to drivers landing page

- source/administration/production-notes.txt
TTL uses replication not clock sync on members of a replica set.
> DOCS-14225: Remove incorrect TTL reference

- source/administration/production-notes.txt
TTL uses replication not clock sync on members of a replica set.
> Remove incorrect TTL reference

- source/includes/extracts-agg-stages.yaml
- source/reference/operator/aggregation-pipeline.txt
- source/reference/operator/aggregation/search.txt
DOCSP-14880 updates for copy review feedback
> DOCSP-14880 Create shell page for Atlas Search

- source/reference/command/killAllSessionsByPattern.txt
I came across this while looking into [DRIVERS-1577](https://jira.mongodb.org/browse/DRIVERS-1577).
Also, whoever merges this may want to also take a look at [SERVER-54216](https://jira.mongodb.org/browse/SERVER-54216). It seems there is an outstanding server bug that contradicts the message in this current documentation. I'm not sure if that's related to [DOCSP-14305](https://jira.mongodb.org/browse/DOCSP-14305), but if not I'd suggest opening a new DOCSP ticket (linked to SERVER-54216) so you don't lose track of that.
> Add missing words in Access Control text

- source/core/index-text.txt
- source/core/text-search-operators.txt
- source/includes/fact-atlas-search-languages.rst
- source/includes/fact-atlas-search-search-stage.rst
- source/includes/fact-text-index-limit-one.rst
- source/reference/operator/query/text.txt
- source/reference/text-search-languages.txt
- source/text-search.txt
- source/tutorial/control-results-of-text-search.txt
- source/tutorial/text-search-in-aggregation.txt
This PR removes the top-level callouts for Atlas Search and replaces them with more contextual callouts in-line, which will hopefully result in a better experience for the user and drive awareness of Atlas Search.
Staged pages:
- Top level [Text Index Page](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCSP-13152/core/index-text.html#create-text-index)
- [Text Search Operators](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCSP-13152/core/text-search-operators.html#aggregation-framework)
- [Text Search in Aggregation Pipeline](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCSP-13152/tutorial/text-search-in-aggregation.html#search-stage-in-atlas-search)
- [Text Search …
> (DOCSP-13152): Improve Atlas Search callouts

- conf-sitemap.xml
During the Croud SEO audit, they found that non-HTML files were included in the sitemap.
> DOP-2048: Drop .tar.gz and .epub files from the sitemap

- config/redirects
Adds redirect to… redirect the genindex page that we are no longer building as of Snooty to the main landing page. Redirect file should be updated to include the earlier versions as they move onto being built with Snooty as well.
> DOP-1882: redirect genindex to homepage

- source/core/read-preference-hedge-option.txt
- source/reference/connection-string.txt
- source/tutorial/upgrade-revision.txt
`/drivers/drivers` and `/drivers/driver-compatibility-reference` are no longer pages in the driver docs, so this edit updates the relevant links to point to the actual drivers documentation site. There's another PR for the updates to v4.4./master.
> DOP-1883: address legacy links to ecosystem docs

- snooty.toml
- source/contents.txt
- source/includes/driver-examples/driver-example-indexes-2.rst
- source/includes/fact-collation-driver.rst
- source/includes/footnote-set-shell-batch-size.rst
- source/includes/steps-run-mongodb-on-linux-tarball.yaml
- source/includes/steps-run-mongodb-on-linux.yaml
- source/includes/steps-run-mongodb-on-osx.yaml
- source/includes/steps-run-mongodb-on-windows.yaml
- source/reference.txt
- source/reference/mongo.txt
- source/reference/program/mongo.txt
- source/tutorial/install-mongodb-enterprise-on-windows.txt
- source/tutorial/install-mongodb-on-windows.txt
This ticket:
- replaces mongo shell with a link to the new mongosh in the left nav
- moves the old mongo link to Reference section
- renames the link to 'Legacy mongo Shell' 
- returns a TOC to the legacy page that had been dropped 
Most of the updated files are included because of path updates in links to the old mongo shell. 
source/reference/mongo.txt is a stripped down version of the older source/mongo.txt landing page
The other changes are to link up the indices and TOCs properly.
https://jira.mongodb.org/browse/DOCSP-15883
https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCSP-15883-left-nav-updates-for-mongo-mongosh-v5.0/
https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCSP-15883-left-nav-updates-for-mongo-mongosh-v5.0/reference/mongo/ …
> DOCS-15883 update left-nav for mongo mongosh

- source/tutorial/manage-the-database-profiler.txt
I don't think we ever put everything in admin.system.profile, and the text already conflicts with itself later on when we do state that system.profile goes in every profiled database.
> Fix database profiler collection location

- source/core/zone-sharding.txt
shard keys don't have values 1, 2, 3...   and you define ranges using shard key, not zones, and to use location it has to be first field (not any one field) in the shard key
> fixing wording

- source/includes/admonition-wsl.rst
MongoDB in WSL is supported - linked to the [official documentation](https://docs.microsoft.com/windows/wsl/tutorials/wsl-database#install-mongodb) as well. I just updated the admonition with a link to the document above.
> Update the WSL guideline

- source/includes/extracts-4.2-changes.yaml
- source/reference/operator/aggregation/accumulator.txt
- source/reference/program/mongod.txt
> fixups for mongod options

- source/tutorial/ensure-indexes-fit-ram.txt
the calculation from Bytes to GB is wrong
> DOCS-14756: Update ensure-indexes-fit-ram.txt

- source/core/index-creation.txt
> DOCS-14756: Update index-creation.txt

- source/indexes.txt
- source/reference/explain-results.txt
- source/release-notes/5.0.txt
DOCS-14453 execution stats inner lookup
> DOCS-14453 execution stats inner lookup

- source/reference/connection-string.txt
@jdestefano-mongo, I added details to the following page about the Atlas UI providing the connection strings.
[STAGE](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCSP-17921/reference/connection-string/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-17931)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6127ecc67dcf01293000e24c)
> (DOCSP-17931): Added Atlas connection string note.

- config/redirects
- source/changeStreams.txt
- source/includes/change-streams-optimization.rst
- source/includes/extracts-agg-operators.yaml
- source/includes/stockSales-example-collection-create.rst
- source/includes/stockSales-example-collection.rst
- source/includes/tsIncrement-introduction.rst
- source/includes/tsSecond-introduction.rst
- source/reference/operator/aggregation.txt
- source/reference/operator/aggregation/tsIncrement.txt
- source/reference/operator/aggregation/tsSecond.txt
- source/release-notes/5.1.txt
DOCSP-15253 changeStream optimization
> DOCSP-15253 changeStream optimization

- source/reference/command/aggregate.txt
This sentence appears to only be applicable to the legacy shell.
> Remove legacy shell tip from aggregate command

- source/includes/downgrade-path.rst
- source/includes/upgrade-downgrade-replica-set.rst
- source/tutorial/upgrade-revision.txt
DOCS-14370 primary hangs when setting FCV
> DOCS-14370 primary hangs when setting FCV

- source/core/link-text-indexes.txt
- source/core/text-search-operators.txt
- source/includes/fact-atlas-search-languages.rst
- source/includes/fact-create-text-index.rst
- source/includes/fact-text-index.rst
- source/includes/fact-text-search-legacy-atlas.rst
- source/includes/fact-use-text-operator.rst
- source/reference/text-search-languages.txt
- source/text-search.txt
- source/tutorial/text-search-in-aggregation.txt
- [JIRA](https://jira.mongodb.org/browse/DOCSP-17260)
- Stage:
- [Text Search](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCSP-17260/text-search/)
- [Text Indexes](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCSP-17260/core/link-text-indexes/)
- [Text Search Operators](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCSP-17260/core/text-search-operators/)
> DOCSP-17260 Direct Text Search traffic to Atlas Search

- source/reference/method/db.getUser.txt
> DOCSP-19331 show user output (#6075)

- source/core/link-text-indexes.txt
- source/core/text-search-operators.txt
- source/includes/extracts-atlas-search-facts.yaml
- source/includes/fact-text-search-legacy-atlas.rst
- source/reference/operator/query/regex.txt
- source/reference/text-search-languages.txt
- source/text-search.txt
- source/tutorial/text-search-in-aggregation.txt
- [JIRA](https://jira.mongodb.org/browse/DOCSP-19125)
- [Stage](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCSP-19125/reference/operator/query/regex/)
> DOCSP-19125 Direct Regex Search traffic to Atlas Search

- source/reference/operator/query/exists.txt
> DOCS-14794 exists update (#6100)

- source/core/timeseries-collections.txt
- source/core/timeseries/timeseries-granularity.txt
- source/core/timeseries/timeseries-limitations.txt
- source/includes/5.1/5.1-release-notes-sharded-time-series.rst
- source/includes/time-series/fact-granularity-description.rst
- source/includes/time-series/fact-meta-field-description.rst
- source/includes/time-series/fact-time-field-description.rst
- source/reference/command/findAndModify.txt
- source/reference/command/shardCollection.txt
- source/reference/method/db.collection.update.txt
- source/reference/method/js-collection.txt
- source/release-notes/5.1.txt
This update covers the changes in:
- [DOCSP-18792: Minimal support for sharding Time Series Collections](https://jira.mongodb.org/browse/DOCSP-18792)
- [DOCSP-16551: Time-Series Collection support for standard delete and update commands](https://jira.mongodb.org/browse/DOCSP-16551)
Staging links:
- [Time Series Sharding Limitations](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/time-series-updates/core/timeseries/timeseries-limitations/#sharding)
- [Time Series Granularity](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/time-series-updates/core/timeseries/timeseries-granularity/#change-the-granularity-of-a-time-series-collection)
- [Time Series Updates and Deletes Limitations](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworke …
> Time series updates for sharding support and updates / deletes

- source/includes/extracts-views.yaml
DOCS-11663 queries-on views implementation
> DOCS-11663 queries on views implementation (#6115)

- source/tutorial/rotate-key-replica-set.txt
> DOCS-14914 keyfile fails to rotate (#6125)

- source/release-notes/5.0.txt
This reverts commit a50431b2d914514bdd139c36b7a9e8c619e5ff94.
> Revert "DOCSP-18626 release note for snippets. (#6145)"

- source/reference/command/collStats.txt
> DOCSP-17199 collStats command does not error (#6172)

- config/redirects
Also: the "symlinks" don't do anything as of Snooty, so removing that cruft to avoid introducing tech debt / confusion.
> Update redirects base for subdomain consolidation

- Makefile
- source/reference/database-references.txt
- source/reference/explain-results.txt
- source/reference/operator/aggregation/geoNear.txt
- source/release-notes/5.0.txt
- source/release-notes/5.3.txt
A story about upgrading:
I just learned that I needed to upgrade MongoDB for a different program to be able to update. No big deal, I'll just go read the steps to upgrade Mongo from v4.0.something.
Ok, gotta add a new apt-source for v... and it wasn't self updating to 4.2... weird. Whatever.
Hmmm, what is this mmapv1 thing? Oh, it's just the default storage type. I just used defaults. Find by me if it gets upgraded to the latest.
`apt upgrade` installs new version...
`mongod` service is still running... weird. Usually apt takes care of that. `sudo systemctl restart mongod`... Wait, it's not coming back up...
No error in syslog... oh right, mongo does it's own logs. Hmmm, mmapv1 support was removed so now it can't start. Weird. Ok, find the migration instructions, basically: `mongodump …
> WIP: Improve documentation about converting from MMAPv1 to WiredTiger

- source/reference/command/serverStatus.txt
> DOCSP-26802 fix typo in serverStatus.txt

- source/includes/analyzeShardKey-limitations.rst
- source/includes/cqa-limitations.rst
changed multi-tenant to shared tier and serverless, also added links 
https://preview-mongodbsonderdonkmdb.gatsbyjs.io/docs/DOCSP-39857/reference/command/configureQueryAnalyzer/
https://preview-mongodbsonderdonkmdb.gatsbyjs.io/docs/DOCSP-39857/reference/command/analyzeShardKey/ 
https://jira.mongodb.org/browse/DOCSP-39857
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=666c5c47ebce19f314e1cba0
See the [taxonomy tagging instructions](https://wiki.corp.mongodb.com/display/DE/Taxonomy+tagging+instructions) and this [example PR](https://github.com/10gen/cloud-docs/pull/5042/files) 
[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)
> DOCSP-39857 changed configureQueryAnalyzer limitations

- source/includes/fact-environments-atlas-support-no-free-or-m10.rst
changed "this command has limited support" to "this command is unsupported" for setParameter compatibility section
https://preview-mongodbsonderdonkmdb.gatsbyjs.io/docs/DOCSP-39569/reference/command/setParameter/#compatibility 
https://jira.mongodb.org/browse/DOCSP-39569
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=666affc2ebce19f3148c3a21
See the [taxonomy tagging instructions](https://wiki.corp.mongodb.com/display/DE/Taxonomy+tagging+instructions) and this [example PR](https://github.com/10gen/cloud-docs/pull/5042/files) 
[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)
> DOCSP-39569 changed limited to unsupported for setParameter

- source/includes/rolling-index-build-cases.rst
Fixes typo in "Rolling Index Build Cases":
https://www.mongodb.com/docs/manual/tutorial/build-indexes-on-replica-sets/#about-this-task
On the rolling index build [page](https://www.mongodb.com/docs/manual/tutorial/build-indexes-on-replica-sets/#about-this-task) for replica sets, in the second bullet of the recommendation, **where reads:
"If your WiredTiger cache fill ratio regularly exceeds 90&" should read: "If your WiredTiger cache fill ratio regularly exceeds 90%"**
Link to staging: https://deploy-preview-6290--mongodb-docs.netlify.app/tutorial/build-indexes-on-replica-sets/
https://jira.mongodb.org/browse/DOCSP-47296
See the [taxonomy tagging instructions](https://wiki.corp.mongodb.com/display/DE/Taxonomy+tagging+instructions) and this [example …
> DOCSP-47296-fix-typo-in-rolling-index-replica-set

- source/reference/command/find.txt
The current docs for the find command still documents oplogReplay, but since version 4.4 it is ignored. However, the flag can still be defined for backwards compatibility, without any effect. 
- Added admonition to describe the behavior of the oplogReplay with versions 4.4 and above
- Deleted the oplogReplay option from unsupported find command fields with Stable API
https://deploy-preview-6295--mongodb-docs.netlify.app/reference/command/find/
https://jira.mongodb.org/projects/DOCSP/issues/DOCSP-43405
See the [taxonomy tagging instructions](https://wiki.corp.mongodb.com/display/DE/Taxonomy+tagging+instructions) and this [example PR](https://github.com/10gen/cloud-docs/pull/5042/files) 
[What's expected of an external reviewer?]
- Review that oplogReplay behavior description …
> DOCSP-43405-msg-oplogReplay-find-command
