mongodb/docs

source/tutorial/authenticate-nativeldap-activedirectory.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2856)

Fix verb tense

---

source/tutorial/remove-documents.txt
source/tutorial/update-documents.txt

@i80and : Fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2893)

(DOCSP-608-fix): Changed over/underlines.

---

source/reference/command/distinct.txt

Removing 'stats' line from JS code blocks
Review: https://mongodbcr.appspot.com/140120001/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2894)

DOCS-8357 Removing stats from distinct command return

---

source/includes/ref-toc-operator-query-geospatial-modifiers.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2892)

DOCS-10384 Typo fix for maxDistance

---

config/redirects.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2898)

DOCSP-701 - Removed redirect to the old shell primer.

---

source/core/sharding-balancer-administration.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2920)

Clarify that sharding migration critical section only blocks operations for the collection being migrated

---

source/reference/operator/aggregation/bucketAuto.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2923)

DOCS-9699 fixed goupBy id typo

---

source/administration/production-notes.txt

Master and 3.4, please!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2942)

DOCS-9655: tweaks to ec2 recommendations

---

source/core/security-ldap-external.txt

.bind was missing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2946)

Fixed queryUser and queryPassword

---

source/includes/templates/tabs-gs.rst
source/includes/templates/tabs.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2918)

Update tabs template to match docs-tools

---

source/reference/operator/query/type.txt
source/release-notes/3.6-compatibility.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2947)

Docs 10226 type array new behavior

---

source/includes/templates/tabs-gs.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2948)

Fix tabs on Getting Started page

---

source/includes/apiargs-dbcommand-aggregate-field.yaml
source/includes/apiargs-method-db.collection.aggregate-options.yaml
source/reference/command/aggregate.txt
source/reference/method/db.collection.aggregate.txt
source/release-notes/3.6.txt

added a comment section for the db.col.aggregate method and modified existing pages to include comment parameter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2955)

DOCS-10020 added comment param documentation to aggregate method

---

source/administration/production-notes.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2966)

prodnotes: clarify vMotion recommendations

---

source/includes/apiargs-method-UUID-param.yaml
source/reference/method/UUID.txt

Updating UUID method input params and providing additional examples.
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-10403/reference/method/UUID.html
Code review: https://mongodbcr.appspot.com/158930001/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2973)

DOCS-10403 - Updates to UUID method

---

source/reference/operator/aggregation/collStats.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2978)

DOCS-10401 - Add count to collStats

---

source/includes/apiargs-dbcommand-createUser-field.yaml
source/includes/apiargs-dbcommand-updateUser-field.yaml
source/release-notes/3.6.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2989)

DOCS-10569 - Updating release notes

---

source/mongo.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3010)

DOCS-10863: Improve documentation on use of reserved words in MongoDB shell

---

source/reference/ulimit.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3009)

DOCS-9912 Fix error message for 3.2

---

source/core/capped-collections.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3065)

DOCS-10030: Improve description of TTL indexes vs capped collections

---

source/core/inmemory.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3078)

fix typo in inmemory note

---

source/reference/command/distinct.txt
source/reference/command/geoNear.txt
source/reference/method/db.collection.distinct.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3080)

DOCS-10539 geoNear and distinct may return orphans

---

source/reference/parameters.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3081)

DOCS-10907 add sharding parameter constraints

---

source/reference/operator/aggregation/divide.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3084)

Fix typo in divide.txt

---

source/core/kerberos.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3086)

DOCS-10989 Update driver support links for Kerberos

---

source/reference/method/db.aggregate.txt
source/tutorial/deploy-shard-cluster.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3093)

remove bracket and s

---

source/reference/built-in-roles.txt
source/reference/privilege-actions.txt

Staging: https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-10860/reference/privilege-actions.html
Code review: https://mongodbcr.appspot.com/167670001/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3098)

DOCS-10860 - Adding privilege to use UUID as namespace

---

source/reference/operator/aggregation/out.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3099)

DOCS-11037 Describe $out stage process

---

source/tutorial/manage-indexes.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3101)

Removed unneeded 'm' character.

---

source/release-notes/3.6.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3103)

Release Notes paragraph for Change Streams

---

Makefile
source/tutorial/change-streams-example.txt

DOCSP-1350 made changes per Kay's feedback
change streams modification
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3104)

moved the default domain line

---

source/includes/currentOp-output-example.rst

Trivial fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3108)

DOCSP-1395: Remove extraneous line in output

---

source/includes/seealso-cluster-manager.rst
source/reference/built-in-roles.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3109)

DOCS-10988: reword all-database roles sections

---

source/reference/command/applyOps.txt

Code review: https://mongodbcr.appspot.com/177050001/
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-11024/reference/command/applyOps.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3123)

DOCS-11024 - Documenting required privileges for applyOps with UUIDs

---

source/core/index-creation.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3115)

DOCS-4578 Clarify global locks for index replication

---

source/includes/access-create-role.rst
source/includes/access-update-role.rst
source/includes/apiargs-dbcommand-createRole-field.yaml
source/includes/apiargs-dbcommand-updateRole-field.yaml
source/includes/apiargs-dbcommand-updateUser-field.yaml
source/includes/apiargs-method-db.createRole-role-field.yaml
source/includes/apiargs-method-db.updateRole-update-fields.yaml
source/includes/fact-auth-restrictions-array-contents.rst
source/includes/fact-auth-restrictions-role-desc.rst
source/reference/command/createRole.txt
source/reference/command/updateRole.txt
source/reference/method/db.createRole.txt
source/reference/method/db.updateRole.txt
source/reference/method/db.updateUser.txt

Code review: https://mongodbcr.appspot.com/173250001/
Staging links: 
https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-10967/reference/command/createRole.html
https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-10967/reference/command/updateRole.html
https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-10967/reference/method/db.createRole.html
https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-10967/reference/method/db.updateRole.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3118)

DOCS-10967 - Add authentication restrictions to createRole and updateRole

---

source/includes/extracts-manage-journaling.yaml
source/includes/options-mongod.yaml
source/includes/warning-disable-journaling.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3127)

DOCS-10928: --nojournal option warning for manual v3.2

---

source/includes/options-mongodump.yaml
source/includes/options-mongorestore.yaml

@rkumar-mongo : Could you give this a look?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3060)

(DOCS-10944, -10705): Added limitations of --oplog and --oplogReplay.

---

source/reference/built-in-roles.txt
source/reference/privilege-actions.txt

Code review: https://mongodbcr.appspot.com/169780001/
Staging: Staging: https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-11059/reference/privilege-actions.html#server-administration-actions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3134)

DOCS-11059 - Documenting forceUUID action

---

source/includes/steps-install-verify-files-pgp.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3129)

Use 3.2 version example and 3.2 key for 3.2 pgp instructions

---

source/faq/fundamentals.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3132)

DOCSP-1439: add BI connector link to FAQ

---

source/includes/wiredtiger-node-nojournal.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3135)

DOCS-11032: update to 3.6 compatibility page for --nojournal option

---

source/includes/fact-session-timeout.rst
source/reference/command/isMaster.txt
source/reference/parameters.txt

[Code Review](https://mongodbcr.appspot.com/171660001/)
[Jira Ticket](https://jira.mongodb.org/browse/DOCS-10676)
Staged:
[isMaster](https://docs-mongodbcom-staging.corp.mongodb.com/nick/DOCS-10676/reference/command/isMaster.html#isMaster.logicalSessionTimeoutMinutes)
[Server Parameter](https://docs.mongodb.com/master/reference/parameters/#param.localLogicalSessionTimeoutMinutes)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3141)

DOCS-10676: logicalSessionTimeoutMinutes updates

---

source/includes/steps-control-access-to-mongodb-windows-with-kerberos-authentication.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3145)

Fix an include inside a note that was not rendering properly.

---

source/reference/connection-string.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3152)

Fix port typo in DNS seedlist example

---

source/core/replica-set-oplog.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3156)

DOCSP-1495: sentence improvement

---

source/includes/options-conf.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3175)

DOCSP-1538: error in net.bindIpAll configuration option

---

source/reference/operator/aggregation/arrayToObject.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3177)

fix spelling

---

source/reference/operator/query/ne.txt

@kay-kim : Made the simple change requested.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3179)

(DOCS-6021): Removed Javascript inequality operator in description.

---

source/reference/connection-string.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3184)

DOCS-11158: Fixed markup syntax on FQDN example

---

source/core/distributed-queries.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3192)

DOCS-11176: Typo: Feature Compabitiliby Version

---

source/reference/read-concern.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3198)

Fixed typo

---

Makefile
source/tutorial/change-streams-example.txt

removed php from change-streams-example.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3199)

DOCSP-1350 with php removed

---

source/tutorial/change-streams-example.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3207)

DOCSP-1623: add 4th change stream example for node

---

source/reference/command/update.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3205)

Fix grammar in section title

---

source/tutorial/manage-the-database-profiler.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3226)

minor: fix typo

---

source/includes/extracts-sessions.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3231)

fix plurals

---

source/core/read-isolation-consistency-recency.txt

'folowing' -> 'following'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3232)

Fix following typo

---

source/core/wiredtiger.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3234)

clarifications on WiredTiger

---

source/release-notes/3.6-compatibility.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3239)

DOCS-11241 - Updating compatibility notes for sorting on multiple array fields

---

source/includes/options-conf.yaml
source/includes/options-mongod.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3238)

DOCS-11343 Add warning about misleading syslog timestamps

---

source/reference/configuration-options.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3235)

DOCS-10346 - Fixing typo in storage.dbPath

---

source/includes/fact-single-modification-in-sharded-collections.rst

Code review: https://mongodbcr.appspot.com/178940001/
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-11163/reference/method/db.collection.remove.html#behavior
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3229)

DOCS-11163 - Fixing note about sharded collections for remove ops

---

conf.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3228)

DOCS-10390: 3.0 eol (feb 27 merge)

---

source/reference/method/rs.printSlaveReplicationInfo.txt

Staging: https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-10359/reference/method/rs.printSlaveReplicationInfo.html#rs.printSlaveReplicationInfo
Code review: https://mongodbcr.appspot.com/190170002/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3247)

DOCS-10359 - Adding point about negative values for printSlaveReplicationInfo()

---

source/includes/extracts-wired-tiger.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3259)

DOCS-11374 Clarify WT cache calculation

---

source/reference/command/compact.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3263)

DOCS-11462 compact may require additional disk space

---

source/includes/3.6-upgrade-enable-features.rst
source/includes/steps-3.6-upgrade-sharded-cluster.yaml
source/release-notes/3.6-upgrade-sharded-cluster.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3273)

DOCSP-2144: 3.6 drivers and 3.6 sharded clusters with 3.4 fcv

---

source/includes/apiargs-dbcommand-fsync-field.yaml
source/includes/ref-toc-command-administration.yaml
source/includes/steps-backup-sharded-cluster-with-snapshots.yaml
source/includes/steps-backup-sharded-clusters-dumps.yaml
source/reference/command/fsync.txt
source/reference/command/fsyncUnlock.txt
source/reference/method/db.fsyncLock.txt
source/reference/method/db.fsyncUnlock.txt
source/tutorial/backup-with-filesystem-snapshots.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3275)

DOCS-9265, DOCS-5976: fsyncLock/Unlock and lock counts

---

source/includes/fact-mongodb-cr-deprecated.rst
source/release-notes/3.0-scram.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3278)

DOCS-11517: Spello: ``MONGODB-CR`` authentication mechanisem

---

source/includes/apiargs-method-db.collection.watch-param.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3294)

DOCS-11574 - Fix typo on db.collection.watch() parameters.

---

source/includes/apiargs-method-db.collection.watch-param.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3293)

 DOCS-11574 - Fix typo on db.collection.watch() parameters.

---

source/reference/command/collMod.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3295)

DOCS-11615: Correct example using collMod to add/update validation

---

source/administration/production-notes.txt
source/includes/fact-platform-s390x.rst
source/includes/fact-platform-x86_64.rst
source/includes/fact-ubuntu-lts-support.rst
source/includes/release-specifications.yaml
source/includes/steps-install-mongodb-enterprise-on-suse.yaml
source/includes/steps-install-mongodb-enterprise-on-ubuntu.yaml
source/includes/steps-install-mongodb-on-suse.yaml
source/includes/steps-install-mongodb-on-ubuntu.yaml
source/tutorial/install-mongodb-enterprise-on-suse.txt
source/tutorial/install-mongodb-on-suse.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3287)

DOCS-11322, DOCS-11531: remove SLES11 and Ubuntu 12.04 support

---

source/core/gridfs.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3298)

DOCS-11628 Add missing word and clarify phrasing

---

config/build_conf.yaml
source/release-notes/3.6.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3299)

DOCS-11554: 3.6.4 release

---

source/reference/explain-results.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3282)

Added SHARD_FILTER info

---

source/includes/intro-zone-sharding.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3261)

there is no such thing as conflicting zones

---

source/reference/change-events.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3311)

incorrect fields included in delete example

---

source/reference/operator/aggregation/subtract.txt

Staged: https://docs-mongodbcom-staging.corp.mongodb.com/caleb/DOCS-11678/reference/operator/aggregation/subtract.html
ticket: https://jira.mongodb.org/browse/DOCS-11678
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3312)

specify milliseconds when subtracting dates

---

source/reference/program/mongoldap.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3313)

MongoDB 3.4 mention in MongoDB 3.6 documentation.

---

source/tutorial/backup-with-filesystem-snapshots.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3321)

DOCS-7661 File system snapshots for backups under WiredTiger

---

source/includes/fact-management-methods-write-concern.rst
source/reference/method/db.createRole.txt
source/reference/method/db.createUser.txt
source/reference/method/db.dropAllRoles.txt
source/reference/method/db.dropAllUsers.txt
source/reference/method/db.dropRole.txt
source/reference/method/db.dropUser.txt
source/reference/method/db.grantPrivilegesToRole.txt
source/reference/method/db.grantRolesToRole.txt
source/reference/method/db.grantRolesToUser.txt
source/reference/method/db.revokePrivilegesFromRole.txt
source/reference/method/db.revokeRolesFromRole.txt
source/reference/method/db.revokeRolesFromUser.txt
source/reference/method/db.updateRole.txt
source/reference/method/db.updateUser.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3322)

DOCS-11378 user and role management methods default write concern

---

source/core/replica-set-rollbacks.txt
source/reference/parameters.txt
source/release-notes/4.0.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3323)

DOCS-11620: rollback param

---

source/reference/built-in-roles.txt
source/reference/command/listDatabases.txt
source/reference/privilege-actions.txt
source/release-notes/4.0-compatibility.txt

Code review: https://mongodbcr.appspot.com/201720002/
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-11103/reference/command/listDatabases.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3324)

DOCS-11103 - Updates to listDatabases command

---

source/includes/steps-create-manually-windows-service-for-mongodb.yaml

@steveren : Quick update to the MongoDB config file formatting.
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/anthonysansone/DOCSP-10233/tutorial/install-mongodb-on-windows.html#create-a-mongodb-configuration-file)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3325)

(DOCS-10233): Clarify configuration file needs for MongoDB conf file.

---

source/includes/options-conf.yaml
source/includes/options-mongod.yaml
source/includes/options-mongos.yaml
source/includes/options-shared.yaml
source/reference/configuration-options.txt
source/reference/program/mongod.txt
source/reference/program/mongos.txt
source/release-notes/4.0-compatibility.txt

Code review: https://mongodbcr.appspot.com/205460001/
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCS-11195/reference/configuration-options.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3326)

DOCS-11195 - Removing transportLayer option

---

source/includes/fact-install-windows.rst
source/includes/fact-timezone-description.rst
source/includes/release-specifications.yaml
source/includes/steps-configure-windows-service-for-mongodb.yaml
source/includes/steps-create-manually-windows-service-for-mongodb.yaml
source/includes/steps-run-mongodb-on-windows.yaml
source/tutorial/install-mongodb-on-windows.txt

@kay-kim : RFM for `master` and `v3.6`. Also fixed an error on the time zone page that broke a build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3328)

(DOCS-11026): Fixed version numbers for directory paths.

---

source/includes/steps-create-manually-windows-service-for-mongodb.yaml

@kay-kim : RFM for `v3.6` and `master`.

(DOCS-10638): Added line about needing to close other command prompts.

---

source/reference/configuration-file-settings-command-line-options-mapping.txt

see https://jira.mongodb.org/browse/SERVER-33123

Mongos does not support --noscripting

---

source/administration/monitoring.txt
source/core/auditing.txt
source/core/authentication-mechanisms-enterprise.txt
source/core/authentication.txt
source/core/backups.txt
source/core/security-encryption-at-rest.txt
source/core/sharding-data-partitioning.txt
source/release-notes/3.6-upgrade-standalone.txt
source/release-notes/4.0.txt
source/replication.txt
source/security.txt
source/sharding.txt
source/tutorial/backup-and-restore-tools.txt
source/tutorial/install-mongodb-on-os-x.txt
source/tutorial/install-mongodb-on-red-hat.txt
source/tutorial/install-mongodb-on-ubuntu.txt
source/tutorial/install-mongodb-on-windows.txt
source/tutorial/manage-the-database-profiler.txt
source/tutorial/manage-users-and-roles.txt

Hey @kay-kim the Atlas SWAT team wants to place some calls to actions (CTAs) in some highly trafficked / Atlas relevant sections of the Docs. Over the next few weeks we'll see how these CTAs perform and will experiment with variants accordingly.
Can you review these changes?
Changes staged at the following pages:
* https://docs-mongodbcom-staging.corp.mongodb.com/kirby/master/tutorial/install-mongodb-on-windows.html
* https://docs-mongodbcom-staging.corp.mongodb.com/kirby/master/tutorial/install-mongodb-on-ubuntu.html
* https://docs-mongodbcom-staging.corp.mongodb.com/kirby/master/tutorial/install-mongodb-on-os-x.html
* https://docs-mongodbcom-staging.corp.mongodb.com/kirby/master/tutorial/backup-and-restore-tools.html
* https://docs-mongodbcom-staging.corp.mongodb.com/kirby/master/tutoria …

Add notes for phase 1 of 20 docs in 20 days

---

source/includes/fact-ObjectId-construct.rst

(DOCS-11844-v3.6): Updated ObjectID description.

---

source/includes/fact-ObjectId-construct.rst

(DOCS-11844-v3.4): Updated ObjectID description.

---

source/tutorial/control-access-to-mongodb-windows-with-kerberos-authentication.txt

@rkumar-mongo : Just changes the option for `setspn.exe`. It will need backports to 3.4, 3.6.

(DOCS-10680): Update setspn option.

---

source/includes/extracts-agg-stages.yaml

Typo: Delete the duplicate word `to`

Typo: Delete the duplicate word `to`

---

source/reference/parameters.txt

Staged: https://docs-mongodbcom-staging.corp.mongodb.com/jdestefano/DOCS-11661/reference/parameters.html#param.failIndexKeyTooLong

DOCS-11661 - Tech review feedback.

---

source/reference/operator/aggregation/toUpper.txt

Fixing typo

---

source/reference/command/compact.txt
source/reference/command/replSetResizeOplog.txt
source/tutorial/change-oplog-size.txt
source/tutorial/resync-replica-set-member.txt

DOCSP-3449: Compact Oplog after Reducing Size

---

source/includes/extracts-agg-operators.yaml
source/includes/intro-aggregation-trigonometry.rst
source/includes/ref-toc-aggregation-operators.yaml
source/meta/aggregation-quick-reference.txt
source/reference/operator/aggregation.txt
source/reference/operator/aggregation/acos.txt
source/reference/operator/aggregation/acosh.txt
source/reference/operator/aggregation/asin.txt
source/reference/operator/aggregation/asinh.txt
source/reference/operator/aggregation/atan.txt
source/reference/operator/aggregation/atan2.txt
source/reference/operator/aggregation/atanh.txt
source/reference/operator/aggregation/cos.txt
source/reference/operator/aggregation/degreesToRadians.txt
source/reference/operator/aggregation/radiansToDegrees.txt
source/reference/operator/aggregation/sin.txt
source/reference/operator/aggregation/tan.txt
source/release-notes/4.2.txt

DOCS-12338: 4.2 Trigonometry Expressions (Aggregation)

---

config/redirects
source/includes/fact-expansion-directive-intro.rst
source/includes/options-mongod.yaml
source/reference/configuration-options.txt
source/reference/expansion-directives.txt
source/release-notes/4.2.txt

Also included in work:
* Build out expansion directive subpage
* Reformat __rest to match more closely our syntax-parameter setup

DOCS-12083: Add __exec expansion directive

---

source/reference/operator/aggregation/out.txt

Misleading statement removed.

---

source/includes/options-mongos.yaml
source/includes/steps-deploy-sharded-cluster-connect.yaml
source/includes/steps-enable-authentication-in-sharded-cluster.yaml

They were partially fixed here https://jira.mongodb.org/browse/DOCS-10417, but there are still occurrences of wrong ports. Fixed them.

Fixed wrong config servers port

---

source/reference/method/db.collection.drop.txt

Syntax was incorrect for the example.

Fix example syntax

---

source/reference/operator/aggregation/dateFromParts.txt

Typo in milliseconds.

---

source/tutorial/install-mongodb-on-os-x.txt

Tried to keep it simple. Decided against additional validation checks, as they should not be required.

OSX Community Installation Page Tweak

---

source/core/views.txt

@kay-kim small tidbit. User feedback was that we don't really define what  view is useful for. While views are a general database concept, I felt this was an easy win for users who are new to databases and are using Mongo as their stepping stone.

DOCS-12697: Define what views can be used for

---

source/aggregation.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3271)

grammar tweak

---

source/reference/operator/update/positional-filtered.txt

Invalid object format correction

---

source/core/query-plans.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3269)

"index filters overrides"→"index filters override"

---

source/includes/driver-example-query-50.rst

Fixed the typo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3116)

Change name to item.

---

source/appendix/security/appendixA-openssl-ca.txt

Hi, I believe this binary was listed incorrectly and proposed a change

Listing mongo binaries correctly

---

source/reference/method/db.collection.dataSize.txt

it's not clear if the size in KB, Bytes, MB, etc...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/3034)

Update docs (size should be defined)

---

source/reference/method/db.collection.updateMany.txt
source/reference/method/db.collection.updateOne.txt

DOCS-12846: Update with aggregation pipeline page has typo

---

source/core/index-text.txt
source/includes/promo-atlas-fts.rst
source/reference/operator/query/text.txt
source/reference/text-search-languages.txt
source/text-search.txt

@kay-kim would appreciate a quick headcheck that I haven't made a critical error somewhere in here.

DOCSP-6927: Atlas Full Text Search Promo

---

source/core/transactions-in-applications.txt
source/core/transactions.txt

Updated the Java transactions options order in the convenient api

---

source/core/gridfs.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-6255?filter=-1
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/docsworker/DOCSP-6255-gridFsDoesntSupportTransactions/core/gridfs.html

Added important tag with snippet on gridfs not supporting transactions

---

source/includes/steps-start-sharded-cluster.yaml
source/includes/steps-stop-sharded-cluster.yaml
source/includes/toc-sharded-cluster-administration.yaml
source/tutorial/restart-sharded-cluster.txt

Add tutorial page for restarting a sharded cluster

---

source/reference/method/db.getCollectionInfos.txt

DOCS-12967 corrected typo: 'must'

---

source/introduction.txt

Supersedes https://github.com/mongodb/docs/pull/3320

Consistently punctuate lists in the introduction page

---

source/reference/method/db.collection.findOneAndReplace.txt

Corrected "projection" typo in code example

DOCS-13037 fix 'projection' typo in code example

---

source/reference/connection-string.txt

Corrected single example formatting

DOCSP-5677 amended example formatting

---

source/reference/system-collections.txt

DOCSP-6723 add system.views entry

---

source/reference/operator/aggregation/group.txt

Staged: https://docs-mongodbcom-staging.corp.mongodb.com/docsworker-xlarge/agg-group/reference/operator/aggregation/group.html#examples
PR: https://mongodbcr.appspot.com/493590005/

Reordering examples on group agg page

---

source/reference/operator/aggregation/unwind.txt

PR: https://mongodbcr.appspot.com/493610050/
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/docsworker-xlarge/DOCS-13043/reference/operator/aggregation/unwind.html

(DOCS-13043): Unwind aggregation improvements

---

source/reference/method/db.createUser.txt

Corrected code example: missing comma.

added missing comma to clientSource line in code sample

---

source/tutorial/configure-auditing.txt

JIRA: https://jira.mongodb.org/browse/DOCS-7329
Code Review: https://mongodbcr.appspot.com/515980044/
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/docsworker-xlarge/DOCS-7329/tutorial/configure-auditing.html#configure-auditing

(DOCS-7329): Updating audit config options to point to mongod page

---

source/reference/method/db.collection.countDocuments.txt

This is for version 4.2.1. It references both the changes for 4.2.1 and the 4.0 series.
Code review: https://mongodbcr.appspot.com/507280007/
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/docsworker-xlarge/v4.2.1/reference/method/db.collection.countDocuments.html#empty-or-non-existing-collections-and-views

(DOCS-12966): Updating behavior for countDocuments on empty collections

---

source/administration/production-notes.txt
source/includes/note-minimum-glibc.rst

DOCS-6203 corrected glibc note, removed include

---

source/tutorial/manage-shard-zone.txt

Update older "Tag" commands to their new "Zone" equivalents

DOCSP-5890 update tag cmds to zone cmds

---

source/reference/configuration-file-settings-command-line-options-mapping.txt

Updated replication and storage verbosity commands to reflect correct subobject command syntax.

DOCS-12633 correct replication and storage verbosity parameters

---

source/includes/steps-uninstall-mongodb-enterprise-on-amazon.yaml
source/includes/steps-uninstall-mongodb-on-amazon.yaml
source/tutorial/install-mongodb-enterprise-on-amazon.txt
source/tutorial/install-mongodb-on-amazon.txt

Updated to elevate permissions on rpm command as well, required for Amazon Linux.

DOCSP-7320 correct rpm command to use sudo on Amazon Linux

---

source/includes/steps-install-mongodb-enterprise-on-amazon.yaml
source/includes/steps-install-mongodb-enterprise-on-red-hat.yaml

Corrected links to Enterprise repos to use Enterprise URLs

DOCSP-7391 update repo link to use Enterprise URL

---

source/administration/production-notes.txt
source/includes/extracts-install-mongodb-manually.yaml
source/includes/fact-installation-bind-ip-default-in-config.rst
source/includes/fact-platform-x86_64.rst
source/reference/ulimit.txt
source/tutorial/install-mongodb-enterprise-on-red-hat.txt
source/tutorial/install-mongodb-enterprise-on-ubuntu-tarball.txt
source/tutorial/install-mongodb-on-red-hat.txt

Platform Support: Add RHEL8 support with 4.2.1

DOCS-13108 Platform Support: Add Rhel8

---

source/includes/fact-selinux-redhat-options.rst

Instructions for permitting /sys/fs/cgroup access for mongod instances running with SELinux enforced.

DOCS-13072 add selinux policy for cgroup memory access

---

source/includes/steps-install-mongodb-on-debian.yaml

Fix Debian Community repo URL to use .org

DOCSP-7408 fix Debian Community repo URL to use .org

---

source/includes/steps-run-mongodb-on-linux-tarball.yaml
source/tutorial/install-mongodb-enterprise-on-ubuntu-tarball.txt
source/tutorial/install-mongodb-on-amazon-tarball.txt
source/tutorial/install-mongodb-on-ubuntu-tarball.txt

Updating data and log dir paths

DOCSP-7259 data and log dir changes and sudo for meeting 3

---

source/includes/options-mongod.yaml
source/reference/parameters.txt

Added missing redactClientLogData parameter.

DOCS-13084 add redactClientLogData parameter

---

source/tutorial/install-mongodb-on-os-x.txt

DOCSP-8003 update brew services to offer version tagging

---

source/reference/operator/aggregation/map.txt

CR: https://mongodbcr.appspot.com/540150001/
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCSP-7568/reference/operator/aggregation/map.html

(DOCSP-7568): Clarifying $map example

---

config/redirects

Just a headcheck that these look good. That should be every page that was added throughout CSFLE work.

DOCSP-8001: Add redirects for 4.0-3.0

---

source/administration/production-notes.txt
source/includes/extracts-install-mongodb-manually.yaml
source/includes/fact-platform-x86_64.rst
source/includes/note-suse-ulimit.rst
source/includes/steps-install-mongodb-enterprise-on-suse.yaml
source/includes/steps-install-mongodb-on-suse.yaml
source/reference/ulimit.txt
source/tutorial/install-mongodb-enterprise-on-suse.txt
source/tutorial/install-mongodb-on-suse.txt

This reverts commit f041a7a08b291315232d9893e8357090b88c2ab0.

Revert "DOCS-13256 add SLES15 support"

---

config/redirects
source/includes/extracts-agg-operators.yaml
source/includes/ref-toc-aggregation-operators.yaml
source/meta/aggregation-quick-reference.txt
source/reference/bson-types.txt
source/reference/operator/aggregation/isNumber.txt
source/reference/operator/aggregation/type.txt
source/reference/operator/query/type.txt
source/release-notes/4.4.txt

Integrated changes from last CR here.

DOCS-12936: [v4.4] new aggregation operator

---

source/includes/fact-let-variable-access-note.rst

Addressing some final comments made by @dstorch.

(DOCS-13264): Wording tweaks to let variable info

---

source/administration/monitoring.txt

Supersedes https://github.com/mongodb/docs/pull/2604

Add Pandora FMS to third party monitoring tools

---

source/tutorial/aggregation-zip-code-data-set.txt

fix order of coordinate pair in description
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs/2905)

DOCS-10430

---

source/includes/fact-confirm-enterprise-binaries.rst
source/tutorial/control-access-to-mongodb-with-kerberos-authentication.txt

https://jira.mongodb.org/browse/DOCSP-9746

DOCSP-9746 Clarify how to add service principals and create keytab files in Kerberos tutorial

---

source/includes/extracts-server-status-projection-base.yaml
source/reference/command/serverStatus.txt
source/release-notes/4.2.txt

Includes Updates to backport DOCS-13435

(DOCS-13435): Add aggregation stage metrics to serverStatus

---

source/core/index-ttl.txt

🔥 Do not merge yet. Waiting for the corresponding Online Archive docs to go live. 🔥

(DOCSP-9903): Mention Online Archive on ttl indexes page

---

source/reference/explain-results.txt
source/release-notes/4.4.txt

- [JIRA](https://jira.mongodb.org/browse/DOCS-13259)
- [Review](https://mongodbcr.appspot.com/616330002/)
- [Stage](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCS-13259/release-notes/4.4.html)

DOCS-13259 doc updates to RN for expand field support

---

source/reference/parameters.txt
source/release-notes/4.4.txt

- [JIRA](https://jira.mongodb.org/browse/DOCS-12960)
- [CR](https://mongodbcr.appspot.com/597190001/)
- Stage: 
- [processUmask](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCS-12960/reference/parameters.html#param.processUmask)
- [RN](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCS-12960/release-notes/4.4.html#new-startup-option-for-mongod)

DOCS-12960 doc for processUmask startup option

---

source/core/replica-set-sync.txt
source/reference/parameters.txt
source/release-notes/4.4.txt

- [JIRA](https://jira.mongodb.org/browse/DOCS-13389)
- [CR](https://mongodbcr.appspot.com/629830001/)

DOCS-13389 Doc for the oplogFetcherUsesExhaust parameter

---

source/core/data-modeling-introduction.txt
source/core/transactions.txt
source/includes/extracts-mongodb-live-2020.yaml
source/introduction.txt

Staged:
- [Transactions: Additional Transactions Topics](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCSP-11016/core/transactions.html#additional-transactions-topics)
- [Data Modeling Introduction: Learn More](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCSP-11016/core/data-modeling-introduction.html#learn-more)
- [Introduction: Rich Query Language](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCSP-11016/introduction.html#rich-query-language)

(DOCSP-11016): Add links to MongoDB.live presentations to docs

---

source/reference/command/find.txt
source/reference/mongodb-wire-protocol.txt

[CR](https://mongodbcr.appspot.com/614920001/)

DOCS-12912 Ignore value of oplogReplay option

---

source/core/sharding-balancer-administration.txt
source/includes/extracts-server-status-projection-base.yaml
source/includes/steps-4.4-upgrade-sharded-cluster.yaml
source/reference/command/cleanupOrphaned.txt
source/reference/command/serverStatus.txt
source/reference/config-database.txt
source/reference/glossary.txt
source/reference/parameters.txt
source/release-notes/4.4.txt

[JIRA](https://jira.mongodb.org/browse/DOCSP-7666)

DOCSP-7666: Investigate changes in PM-812: Resumable RangeDeleter

---

source/core/data-modeling-introduction.txt
source/core/transactions.txt
source/includes/extracts-mongodb-live-2020.yaml
source/introduction.txt

(DOCSP-11016): Add links to .live presentations to docs

---

source/reference/parameters.txt
source/release-notes/4.4.txt

- [CR](https://mongodbcr.appspot.com/621480001/)

DOCS-13488 feature flag to turn on/off catalog cache refresh 

---

source/index.txt

[Jira](https://jira.mongodb.org/browse/DOCSP-11308)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/stevenrenaker/DOCSP-11308/index.html)

DOCSP-11308: [Server] Minor tweaks to manual landing page

---

source/crud.txt

changed 'retrieves' to ''retrieve'

Update crud.txt - small grammatical correction

---

source/reference/method/db.collection.ensureIndex.txt

Ensure index is not an alias for create index

Correct note on deprecation

---

source/tutorial/getting-started.txt

Change from "assumes" to "assume"

Document update

---

source/tutorial/backup-and-restore-tools.txt

Change the grammar of using "the" articles (was used twice like "the the")

Change grammar at "backup-and-restore-tools.txt"

---

source/includes/fact-getSecondaryOk.rst
source/includes/fact-secondaryOk.rst
source/includes/fact-setSecondaryOk.rst
source/includes/steps-backup-sharded-cluster-with-snapshots.yaml
source/includes/steps-backup-sharded-clusters-dumps.yaml
source/reference/method.txt
source/reference/method/Mongo.getSecondaryOk.txt
source/reference/method/Mongo.setSecondaryOk.txt
source/reference/method/js-connection.txt
source/reference/method/js-replication.txt
source/reference/method/rs.secondaryOk.txt
source/reference/replication.txt
source/release-notes/3.4-downgrade-replica-set.txt
source/release-notes/3.4-downgrade-sharded-cluster.txt

DOCSP-11989 Slave ok no longer documented

DOCSP-11989 Slave ok no longer documented

---

source/reference/operator/aggregation/lookup.txt

- [Stage](https://docs-mongodbcom-staging.corp.mongodb.com/c51d9a853/docs/docsworker-xlarge/DOCSP-15576/reference/operator/aggregation/lookup/#sharded-collection-restrictions)

DOCSP-15576 adding reference to adl for lookup on sharded collection

---

source/reference/operator/aggregation/getField.txt

fix build warning introduced in #5584

(DOCSP-17440): fix build issue introduced in DOCSP-17440

---

source/reference/operator/aggregation.txt
source/reference/operator/aggregation/setField.txt
source/reference/operator/aggregation/unsetField.txt
source/release-notes/5.0.txt

CR: https://mongodbcr.appspot.com/795320007/

Docsp 16148 add unset field alias for set field v5.0

---

source/reference/connection-string.txt

[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=612d31837dcf0129302a7d89)
* (DOCSP-17931): Added Atlas connection string note.
* (DOCSP-17931): Incorporated Jeff's feedback.
* (DOCSP-17931): Incorporated Jeff's feedback.
* (DOCSP-17931): Incorporated JD's feedback.

(DOCSP-18432): Backport DOCSP-17931 to v5.0. (#5755)

---

source/reference/database-references.txt

* (DOCSP-18425): Add Go to Driver Support for DBRefs table
* fix alphabetization

(DOCSP-18425): Add Go to Driver Support for DBRefs table (#5767)

---

source/reference/connection-string.txt

@jeff-allen-mongo and @jdestefano-mongo, I updated the following Atlas registration link:
[STAGE](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCSP-17931/reference/connection-string/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-17931)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6138c0b57dcf012930c45e96)

(DOCSP-17931): Updated link.

---

source/reference/connection-string.txt

[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=613a4519c608bec57fd8a0bf)
* (DOCSP-17931): Updated link.
* Update source/reference/connection-string.txt
Co-authored-by: jdestefano-mongo <jonathan.destefano@10gen.com>

(DOCSP-18602): Backport DOCSP-17931 to v5.0. (#5815)

---

source/includes/fact-update-operator-lexicographic-order.rst
source/reference/operator/update.txt
source/reference/operator/update/addToSet.txt
source/reference/operator/update/bit.txt
source/reference/operator/update/currentDate.txt
source/reference/operator/update/each.txt
source/reference/operator/update/inc.txt
source/reference/operator/update/max.txt
source/reference/operator/update/min.txt
source/reference/operator/update/mul.txt
source/reference/operator/update/pop.txt
source/reference/operator/update/position.txt
source/reference/operator/update/positional-all.txt
source/reference/operator/update/positional-filtered.txt
source/reference/operator/update/positional.txt
source/reference/operator/update/pull.txt
source/reference/operator/update/pullAll.txt
source/reference/operator/update/push.txt
source/reference/operator/update/rename.txt
source/reference/operator/update/set.txt
source/reference/operator/update/setOnInsert.txt
source/reference/operator/update/slice.txt
source/reference/operator/update/sort.txt
source/reference/operator/update/unset.txt

Revert "DOCS-14472 update operators act in lexicographic order"

---

source/reference/built-in-roles.txt

This reverts commit c7e6721060dd63c360e4d01e7890d6a0d3085b42.

Revert "DOCS-14826 readWrite role has changeStream privilege"

---

source/faq/fundamentals.txt
source/reference/method/db.createCollection.txt

Revert "DOCSP-14047 add note about mongoshell to page"

---

source/includes/downgrade-path.rst
source/includes/upgrade-downgrade-replica-set.rst
source/tutorial/upgrade-revision.txt

DOCS-14370 primary hangs when setting FCV

DOCS-14370 primary hangs when setting FCV

---

source/reference/operator/aggregation/sample.txt

DOCS-14855 reword-sample (#6012)

---

source/core/transactions.txt

DOCS-14791 default write concern (#6079)

---

source/core/transactions-production-consideration.txt

DOCS-14887 wired tiger transaction limit (#6087)

---

source/reference/operator/query/exists.txt

DOCS-14794 exists update (#6100)

---

source/includes/extracts-views.yaml

DOCS-11663 queries-on views implementation

DOCS-11663 queries on views implementation

---

source/includes/extracts-views.yaml

DOCS-11663 queries-on views implementation

DOCS-11663 queries on views implementation (#6115)

---

source/tutorial/rotate-key-replica-set.txt

DOCS-14914 keyfile fails to rotate (#6125)

---

source/includes/fact-selinux-redhat-options.rst

DOCSP-19049 SELinux custom port (#6141)

---

source/reference/command/setFeatureCompatibilityVersion.txt

DOCS-14888 setFeatureCompatibilityVersion wtimeout (#6167)

---

source/reference/command/collStats.txt

DOCSP-17199 collStats command does not error (#6172)

---

source/includes/analyzeShardKey-limitations.rst
source/includes/cqa-limitations.rst

Backports #6277 to v7.0
Build https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=666c8731ebce19f314ee00e2

DOCSP-39857 changed configureQueryAnalyzer limitations (#6277)
